### ISSUE TITLE
Request iNES mapper 31 support

### ISSUE THREAD

**Issue by bbbradsmith** [0ldsk00l/nestopia#142]
Would you consider implementing this mapper: http://wiki.nesdev.com/w/index.php/INES_Mapper_031

Test ROM: http://rainwarrior.ca/projects/nes/2a03puritans.nes

It's a simple mapper, a small subset of the NSF format capabilities, intended mainly for musical ROMs. It is fairly new, so far used in only one homebrew release but more are coming. I can provide other test ROMs if necessary.

**Comment by rdanbrook** [comment]
I will add it to the list. I have to admit, I am somewhat new to implementing new mappers but I am getting a crash course right now and my knowledge is increasing exponentially. It appears this mapper uses registers that are not implemented in Nestopia yet. There is another homebrew rom I've come across that uses the same registers...

**Comment by bbbradsmith** [comment]
Sourceforge seems to be down right now, but this is what the implementation of the mapper looks like in FCEUX:
http://pastebin.com/3DyLmCM9

Not a lot of code. No IRQ, CHR banking, or anything unusual, just 8 PRG banks. It should be similar in function to discrete logic mappers, like maybe look at AxROM (mapper 7) for an example mapper to start from?

**Comment by bbbradsmith** [comment]
Here's a second test ROM if you need it: https://dl.dropboxusercontent.com/u/883356/pico.nes

Just a word of caution, since I notice MESS has a problem right now (and puNES had the same problem in an earlier version): The ROM size could be any power of 2. The 2A03 Puritans album is the maximum 1MB but this one is 512k (and it could be smaller). The high bit of the bank becomes irrelevant in 512k (e.g. $FF and $7F address the same bank), etc.

**Comment by dragon2snow** [comment]
![20150728095332](https://cloud.githubusercontent.com/assets/4350811/8921907/a538dab8-350e-11e5-8f30-1f8acf73be17.png)
thank you share this rom

**Comment by bbbradsmith** [comment]
Cool!

**Comment by dragon2snow** [comment]
this fceux core

**Comment by bbbradsmith** [comment]
I'm confused by that? Anyhow, please do not share the ROM publicly yet. It will be released officially soon.

**Comment by dragon2snow** [comment]
OK, I am used to the nestopia interface, so call  fceux core

**Comment by rdanbrook** [comment]
@dragon2snow, if you have implemented this in Nestopia it would be great if you both share source code, and whatever it is you happen to be smoking.

**Comment by bbbradsmith** [comment]
I've created a series of test ROMs:
http://rainwarrior.ca/projects/nes/31_test_16.nes
http://rainwarrior.ca/projects/nes/31_test_32.nes
http://rainwarrior.ca/projects/nes/31_test_64.nes
http://rainwarrior.ca/projects/nes/31_test_128.nes
http://rainwarrior.ca/projects/nes/31_test_256.nes
http://rainwarrior.ca/projects/nes/31_test_512.nes
http://rainwarrior.ca/projects/nes/31_test_1024.nes

Note that the startup mode should say RESET if soft reset, and POWER ON if hard reset. Otherwise the display should be straightforward. FCEUX beta and Nintendulator beta can be used to compare correct results: http://www.emucr.com/2015/07/fceux-svn-r3139.html
