### ISSUE TITLE
Mapper 22 CHR banking subtly wrong

### ISSUE THREAD

**Issue by lidnariq** [0ldsk00l/nestopia#147]
I discovered a bug in Nestopia's implementation of VRC2a = mapper 22.

Nestopia implements the CHR banking registers as:
`$B000 : [...D EFG.]`
`$B002 : [.... ABC.]`
but the hardware (and Nintendulator and FCEU(X)) does this:
`$B000 : [.... EFG.]`
`$B002 : [.... ABCD]`

This bug was masked because both m22 games use their CHR banking with something equivalent to
`STA $B000`
`LSR`
`LSR`
`LSR`
`LSR`
`STA $B002`
causing 'D' to be written to both locations.

A validation ROM is available at http://forums.nesdev.com/viewtopic.php?p=153176#p153176

**Comment by rdanbrook** [comment]
Will look into this soon, going on a dev rampage shortly.

**Comment by joepogo** [comment]
Hey lidnariq, is this easy to fix?

**Comment by creambits** [comment]
source\core\board\NstBoardKonamiVrc2.cpp

```
template<uint OFFSET>
void Vrc2::SwapChr(uint address,uint subBank) const
{
	ppu.Update();
	if (chrShift == 1)
	{
		if (OFFSET == 0)
			chr.SwapBank<SIZE_1K>( address, (chr.GetBank<SIZE_1K>(address) & 0xF8U) | ((subBank >> 1 & 0x7) << 0) );
		else
			chr.SwapBank<SIZE_1K>( address, (chr.GetBank<SIZE_1K>(address) & 0x07U) | ((subBank >> 0 & 0xF) << 3) );
	}
	else
		chr.SwapBank<SIZE_1K>( address, (chr.GetBank<SIZE_1K>(address) & 0xF0U >> OFFSET) | ((subBank & 0xF) << OFFSET) );
}
```

Passes the rom test.

**Comment by joepogo** [comment]
Thanks for posting this up creambits! Do you know if this is accurate or effects anything adversely?

**Comment by creambits** [comment]
I'm not experienced with mappers but demo rom is picky about m22 accuracy and I haven't noticed anything goofy yet playing some known games. But I posted here in case anyone else sees something wrong.
