### ISSUE TITLE
NES 2.0 implementation does not respect CHR-RAM field

### ISSUE THREAD

**Issue by dustmop** [0ldsk00l/nestopia#148]
Here is a test rom: https://www.dropbox.com/s/eoddy7v83ep6rqu/test-rom.nes?dl=0 It specifies the MMC3 mapper (ines 4) with 32k of CHR-RAM in the NES 2.0 header (byte 11). It does the following:
1) Validates the amount of chr-ram by switching to each 4k of chr-ram and writing a byte, then reading it back.
2) Display the message "OKAY" with a white background if the validation succeeds.
3) Changes the background to red with an error message if the validation fails.

The rom passes on the latest fceux builds, on Powerpak with powermappers, or OpenNestopia with patched in NES 2.0 support. It fails on emulators without NES 2.0 support.

On Nestopia UE, which should have NES 2.0 support, the board detection code in core/board/NstBoard.cpp assumes the rom is TxROM, and treats the CHR-RAM as 32k of CHR-ROM. So the test rom display the red background but doesn't have any text because ram cannot be filled. I tried tracing the code to debug the issue deeper, but I couldn't figure out what NstBoard is supposed to be doing.

Respecting the NES 2.0 header means that the CHR-RAM value should always be used for ram, not for rom.

**Comment by dustmop** [comment]
Correction: My original description was against patched code, not HEAD, where I had tried forcing the CHR-RAM size in NstCartridge.cpp before calling SetupBoard, just to see where to begin making a fix. However, HEAD is still broken, it just displays the error message.

NesCartridgeInes correctly sees 32k of CHR-RAM, but NesBoard does not, and I believe the problem is in the detection code somewhere.

**Comment by rdanbrook** [comment]
Will look into it soon.

**Comment by dustmop** [comment]
What is the goal of NstBoard? Is it just to try and calculate physical hardware based upon specs using heuristics? If so it may be incompatible with NES 2.0 files, since they often represent games that don't exist, or don't exist yet. This is coming from the perspective of a homebrew developer, for whom NES 2.0 is useful, precisely because it doesn't need to correlate to an exact piece of hardware.

Maybe the answer is to treat the chr-ram field specially, or to calculate the board based upon the iNes 1.0 header, then apply NES 2.0 afterwards.

**Comment by LodanZark** [comment]
NewRisingSun has one of the best iNES2.0 headers db: https://forums.nesdev.com/viewtopic.php?f=3&t=19940&p=248994

**Comment by rdanbrook** [comment]
This is fixed since the latest merge.
