### ISSUE TITLE
[Enhancement] Nestopia Support for Proper FDS Dumps

### ISSUE THREAD

**Issue by Buddybenj** [0ldsk00l/nestopia#149]
I have no idea if you are interested in supporting this, but here are some proper FDS dumps: https://drive.google.com/open?id=0B8rgKAMnFwxpUUM3V0ZYUWpYamM

The raw files are low level dumps (I think it's either MFM or magnetic flux).
The bin files are just like normal FDS files but they also include the CRC and gap data that the old dumps were missing.
The FDS files are normal FDS files that work in all FDS emulators.

All of these dumps were from sealed disks. Also, credit goes to HardcoreHubz for buying and dumping these games.

**Comment by dragon2snow** [comment]
what?
16 byte heard+A+B is working fine.
you have emu switch disk?

**Comment by rdanbrook** [comment]
I will take a look at it, this looks like it might be worthwhile to support.
