### ISSUE TITLE
Unix: Weird behavior on single joystick with a lot of buttons

### ISSUE THREAD

**Issue by anthonyagresta** [0ldsk00l/nestopia#153]
I have a MAME cabinet that sends 2 players' worth of inputs as one 4-axis joystick and like 24 buttons.
Several of the buttons seem to all register as the same button. 
I'm inclined to blame this code, `/source/unix/input.cpp:320`

``` c++
                    if (j >= NUMBUTTONS) { input.player = 1; }
                    // This is really dirty
                    if (j == 8 || j == 18) { input.turboa = 1; }
                    if (j == 9 || j == 19) { input.turbob = 1; }
```

Would it be worth reworking this a bit so that controllers with a ton of buttons worked correctly?
Increasing `NUMBUTTONS` in `input.h` might be enough.
Something like 32 buttons seems like a reasonable cap. (I'm sure at the time 10 buttons seemed like a reasonable cap, too.)

If I get the time, I'll fiddle around and see if I can put together a PR, but I figure it's nice to know about either way.

Thanks,

Anthony

**Comment by rdanbrook** [comment]
NUMBUTTONS is not to define buttons from the input device, but the NES controller itself:
Up, Down, Left, Right, Select, Start, A, B, Turbo A, Turbo B

There is probably something else going on. Can you give me more details on the input device? I have built a MAME cabinet so I do know something about arcade controls.

**Comment by anthonyagresta** [comment]
It uses the hid-xinmo driver, it shows up as one device at /dev/input/js0.
If I run jstest, it shows 4 axes and 22 buttons. Player 1 seems to work
okay if I use buttons 0-3, but when I try and assign some of the
higher-numbered buttons to player 2, several of them seem to map to button
1 for some reason. I don't have it in front of me right now, but I can get
more details on Monday.

The wiring is okay, each button corresponds correctly to a separate button
in jstest.

Thanks for the reply, please let me know if anything else would help.
