### ISSUE TITLE
Nestopia not output the MMC5 raw PCM channel

### ISSUE THREAD

**Issue by zerofalcon** [0ldsk00l/nestopia#165]
Hi! I was "googleing" some NES hacks and found this Super Mario All Stars NES version, it is an impressive hack. The autor said in his post that Nestopia is not outputting the MMC5 raw pcm channel, therefore, there is no cheering (myke tyson's cheering sample) at the intro screen. He posted a posible solution by enabling the MMC5 Raw PCM channel (register $5011).
There is the page with his post:
http://acmlm.kafuka.org/board/thread.php?id=8211

I know it seems more like a petition than an issue, but if this can be fixed it would be great! Thanks in advanced and keep up the good work.

**Comment by rdanbrook** [comment]
It's something other people have brought up to me in the past, and it may happen one day. I am writing an emulator from scratch on the side and it is greatly increasing my knowledge, so it is possible I can make this happen once I get to the APU stage and fully understand it.

**Comment by zerofalcon** [comment]
Thank you!

**Comment by dragon2snow** [comment]
nestopia MMC5 raw PCM channel is supported.
solution not by enabling the MMC5 Raw PCM channel (register $5011).!!
solution 6502 fisrt write register0 $5010,select write mode or read mode.
write $5010 value 00.last write 5011 pcm samlpe date

**Comment by joepogo** [comment]
Could you show us some code to get this working dragon2snow? Please?

**Comment by dragon2snow** [comment]
This isn't BUG, and it isn't necessary to fix.

**Comment by joepogo** [comment]
I know its not a BUG. Im asking if you know how to make it where 5011 is output. Do you know how to do it?

**Comment by dragon2snow** [comment]
rom,write 5010,value 00,

**Comment by rdanbrook** [comment]
Don't worry, I know how to do it. It's just a matter of working it into Nestopia's heavily templated C++ codebase, and having the luxury of free time to do so :).

**Comment by joepogo** [comment]
Hey rdanbrook, is this a trivial fix or one that is pretty difficult? If so, will it affect any other games that utilize the ouput of the channel? IIRC its a mahjong game or the like.

**Comment by rdanbrook** [comment]
It should be fairly easy to fix once I put my mind to it. It's just a matter of sitting down and having enough time to integrate my brain with that part of the source code one weekend.

**Comment by joepogo** [comment]
Hey Rdanbrook, do you know by chance which files in nestopia would need to be modified to get this to work?

**Comment by therealinfidelity** [comment]
This is infidelity, the creator of Super Mario All-Stars NES. I found this conversation within google, and took the advice from "dragon2snow" regarding the mmc5 $5010 register. So now the cheering sfx works correctly as an mmc5 pcm sample on nestopia.

I will be releasing a newer update to my project hopefully within a few days.

Check here for my next release.

http://acmlm.kafuka.org/board/thread.php?id=8211

-infidelity
