### ISSUE TITLE
SOROM games not loading/saving PRG RAM (WRAM) correctly

### ISSUE THREAD

**Issue by koitsu** [0ldsk00l/nestopia#178]
There are 3 Koei games (Romance of the Three Kingdoms, Nobunaga's Ambition, and Genghis Khan), all of which are SOROM games, whose native save capability (i.e. PRG RAM/WRAM) doesn't appear to work correctly.  After saving, when power-cycling and attempting to load saved data, the games will simply say "No saved data".

It's suspected that the reason this doesn't work is that Nestopia is either loading or saving the wrong 8KB PRG RAM page.  Specific to SOROM boards, we have this, per the nesdev wiki -- note the last line:

> SOROM uses a similar method, using the second-highest CHR bank select line to choose between two 8KB PRG RAM chips. Of chip 0 and chip 1, only chip 1 is battery backed.

I don't have a patch for this because the PRG RAM/WRAM and save file code is very complex, so I'm not even sure where the problem lies.

Steps to reproduce:
1. Make sure there's no existing .sav file
2. Run NestopiaUE
3. Load Genghis Khan (Genghis Khan (U).nes -- CRC 2225C20F)
4. Start the game, e.g.: Mongol Conquest, set parameters automatically, view no princes, etc.
5. Choose Pass (to move to the next season)
6. Choose Other, then Save; wait for message "Data saved"
7. Power-cycle the emulator via Machine menu (or exit/restart emulator)
8. Choose "Load daved data"

It's hard to tell from the .sav file if the data stored is correct or not (e.g. character names in ASCII are there, but that could be data from PRG RAM page 0 rather than 1; unsure!), so it's difficult to determine if the issue is with loading, or with saving.

Discussion thread: http://forums.nesdev.com/viewtopic.php?f=3&t=14205
SxROM details: http://wiki.nesdev.com/w/index.php/SxROM
HVC-SOROM games: http://bootgod.dyndns.org:7777/search.php?unif=HVC-SOROM
NES-SOROM games: http://bootgod.dyndns.org:7777/search.php?unif=NES-SOROM

**Comment by dragon2snow** [comment]
using nstdatabase.xml

**Comment by joepogo** [comment]
So, how to fix this dragon2snow?

**Comment by dragon2snow** [comment]
try two solution:
1.using nstdatabase.xml
  <game>
        <cartridge system="NES-NTSC" dump="ok" crc="2225C20F" sha1="209911D7BD15ABB7BEF2E35A473DF725B6738CD7">
            <board  mapper="1">
                <prg size="256k" />
                <vram size="8k" />
                <wram size="16k" />
                <wram size="16k" battery="1" />
                <chip type="MMC1B2" />
            </board>
        </cartridge>
    </game>

2.SOROM 
STD_SOROM                  = MakeId<    1,  256,    0,  16,  16, CRM_8,  NMT_H,  0 >::ID,

**Comment by joepogo** [comment]
Thank you, if we opt for solution 2. Then what file is that in the source? I will probably add that entry into the database as well.

**Comment by koitsu** [comment]
For the 2nd solution, it would be source/core/board/NstBoard.hpp.  I still don't know which is the "proper" solution, nor have I verified either of them work.

My concern with the 2nd solution is, just at first glance (I have not looked at how that enum is being used), that it increases the PRG RAM size to 16KB in some manner.  Does this mean 16KB gets written to the .sav file?  If so, I don't see how that's accurate -- information clearly shows that only PRG RAM page 1 is battery-backed, and each page is 8KB.

**Comment by joepogo** [comment]
Ill give these a try when I get home. have you tried either one of these koitsu yet?

**Comment by koitsu** [comment]
Nope; I don't have a VM built for Visual Studio projects.

**Comment by dragon2snow** [comment]
I've only been provide test solution, but is not accurate, I don't want to promise

**Comment by joepogo** [comment]
So really, neither route is accurate?

**Comment by joepogo** [comment]
Wouldn't the easy way to fix this just edit these three games in the xml file to save?

**Comment by joepogo** [comment]
Correction, editing the xml is definitely not the way to do it and hacking up the xml to save in 32kb is NOT correct either. 

Looks like save and load functionality will need to be looked at in NST board for MMC1 i think instead.

**Comment by dragon2snow** [comment]
<game>
 <cartridge system="NES-NTSC" dump="ok" crc="2225C20F" sha1="209911D7BD15ABB7BEF2E35A473DF725B6738CD7">
 <board mapper="1">
 <prg size="256k" />
 <vram size="8k" />
 <wram size="16k" />
 <wram size="16k" battery="1" />
 <chip type="MMC1B2" />
 </board>
 </cartridge>
 </game> 100% working...

**Comment by joepogo** [comment]
So, what did you do dragon to fix? How?
