### ISSUE TITLE
Shinobi (unl) nes graphic glitches

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#181]
On the masked ninja levels, which i think is the last set of levels before you beat the game, there are numerous glitches on the right side of the screen when scrolling. 

https://www.youtube.com/watch?v=dVbVQY3QNMo

On this video for example the levels in question start at: 12:51. The masked ninja levels. On nestopia the levels scrolling gets messed up as you progress in the level. Seems to maybe a mirroring issue possibly. 

Ive tested numerous dumps so its not a bad rom and something is def off unless i am completely crazy.  Maybe some others can confirm this as well.

**Comment by rdanbrook** [comment]
Got any save states that might make it easier to diagnose?

**Comment by joepogo** [comment]
Ill see if I can upload one here. Dragon where are you? I know you have seen this issue too. I wonder if it is a regression from adding the mapper changes for Hard Drivin? Im going to test this out first and then upload a save state here.

**Comment by dragon2snow** [comment]
I am in China, 
Can not access youtube!

**Comment by joepogo** [comment]
http://www.gamepilgrimage.com/sites/default/files//NESpics/Shinobi0045.png

This is a screenshot of the level dragon. Its toward the end of the game. It starts ok, but as you get to the end of the level the mirroring or something gets messed up and becomes a pain in the ass. The level after this also starts doing it as well. 

I checked to make sure this isn't normal on the real nes, and this is not supposed to happen. Its The Masked Ninja level set. Im going to test a build of nestopia first without the hard drivin changes first just to make sure. 

If you remember, the hard drivin scoreboard is not totally accurate as part of the odometer is missing, the top is clipped off.

**Comment by dragon2snow** [comment]
gamepilgriimage.com in china.
Can not access !

**Comment by joepogo** [comment]
Ok here is an attached image. 
![shinobi0045](https://cloud.githubusercontent.com/assets/6021189/15476111/56f22008-20db-11e6-8171-85c5ef2dae0a.png)

**Comment by joepogo** [comment]
Ok, can confirm this is NOT a regression from the hard drivin. The bug has existed for quite some time. I wonder if it is a dabtabase error possibly. But the mirroring def seems to be off and i wonder if this is just a one game issue but i think another tengen game skull and crossbones has an issue with the split screen shaking in 2 player.

**Comment by joepogo** [comment]
this should fix ALL the tengen games and be able to close the Rambo-1 issue opened.

/* Tengen RAMBO1
- If Reset reg ($C001) was written to after previous clock...
     a)  reload IRQ counter with IRQ Reload value **PLUS ONE**
- Otherwise... If IRQ Counter is 0...
     a)  reload IRQ counter with IRQ Reload value
- Otherwise...
     a)  Decrement IRQ counter by 1
     b)  If IRQ counter is now 0 and IRQs are enabled, trigger IRQ
 */
static inline void rambo1_clock(void)
{   
   if(MMC.irq_reset)
   {
      MMC.irq_counter = MMC.irq_latch+1;
      MMC.irq_reset = 0;
   }
   else if(0 == MMC.irq_counter)
   {
      MMC.irq_counter = MMC.irq_latch;
   }
   else
   {
      MMC.irq_counter--;
      if((0 == MMC.irq_counter) && MMC.irq_flag && (-1 == m64_irq))
         m64_irq = 3;
   }
}

static void irq_rambo1(const unsigned int scanline, const unsigned int ppuflag)
{
   if(m64_irq > 0)
      m64_irq--;
   if(0 == m64_irq) {
      cpu_irqtrigger(TIRQ_MPR);
      m64_irq = -1;
   }
   if(0 != MMC.write)
   {
      if(0 == MMC.irq_timing) {
         rambo1_clock();
         MMC.irq_timing = 3;
      } else
         MMC.irq_timing--;
   }
   else
   {
      if( !ppu_is_rendering() ) { irq_latency = 8; return; }
      if(irq_latency > 0)
         irq_latency--;
      if(!irq_latency && ppuflag)
         rambo1_clock();
      if(ppuflag)
         irq_latency = 8;
   }
}

**Comment by dragon2snow** [comment]
rnes521 not working shinobi.
rnes521   using this code?

**Comment by joepogo** [comment]
Not sure where this code came from. Zepper put it on nesdev on the thread.

**Comment by joepogo** [comment]
wait, are you saying shinobi DOES NOT work on rnes either?

**Comment by dragon2snow** [comment]
yes,i test rnes521 zepper version,shinobi not working.

**Comment by joepogo** [comment]
I dont think this is rnes code though. I think he gave us this so we could fix the tengen rambo1 mapper. I think its just the pertinent info we need. Can you make anything out of what we can do to fix it dragon?

**Comment by dragon2snow** [comment]
no,I can't fix, I'm not sure he is right 。Please provide all of the original video cassettes and test

**Comment by joepogo** [comment]
so, dragon you tested this and fixed it by posting a video on nesdev. So, what did you do exactly to get shinobi and skull and crossbones to work in 2 player without shaking? Or are you going to tell me that you deleted and lost the code?

**Comment by joepogo** [comment]
Does anyone know if this could be a mirroring issue?

**Comment by rdanbrook** [comment]
Not sure if this was fixed when I did the recent merge or not, but it doesn't seem to be a problem now.
