### ISSUE TITLE
(multiplatform) selectable aspect ratio drop-down list

### ISSUE THREAD

**Issue by eugene-s-nesdev** [0ldsk00l/nestopia#202]
Accordings to pull-request for libretro and aspect ratio change depending region:
https://github.com/rdanbrook/nestopia/pull/201
https://github.com/rdanbrook/nestopia/commit/cd13ccbb3096b3ede21c895ce18578f13926cfbe

Can you add drop-down list to multiplatform port, which contain:

> auto
> ntsc
> pal
> 4:3

aspect ratios. Auto mode will set NTSC aspect ratio (8:7) for NTSC/Famicom and PAL aspect ratio (1.3862:1) for PAL/Dendy, as well, as it done by arakerlu (#201)

> Option "4:3" is removed on libretro because I don't see any need for it and seems rather arbitrary and redundant - if you want to use it you can set it in frontend/Retroarch.

4:3 (or 5:4 PAR) is useful too, don't remove it please, just make it selectable.
frontend/Retroarch aspect ratio better set to "core provided" all the time, i guess.
User can switch cores between nestopia and gambatte, for example. 
Not comfortable to switch AR every time you change core.

**Comment by rdanbrook** [comment]
Done, after nearly 8 years. I hope you weren't holding your breath.
@eugene-s-nesdev I am not very familiar with PAL, so if you can let me know if this solution is suitable that would be great.

**Comment by eugene-s-nesdev** [comment]
Hi, rdanbrook! Thank you!
I cannot compile it under old mint 19.3

```
 CXX      source/core/board/nestopia-NstBoardBmc120in1.o
 CXX      source/fltkui/nestopia-audiomanager.o
 CXX      source/fltkui/nestopia-chtmanager.o
 CXX      source/fltkui/nestopia-inputmanager.o
source/fltkui/inputmanager.cpp:26:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:7364: recipe for target 'source/fltkui/nestopia-inputmanager.o' failed
make: *** [source/fltkui/nestopia-inputmanager.o] Error 1
```

**Comment by eugene-s-nesdev** [comment]
Hi, @rdanbrook Thank you!
I cannot compile it under old mint 19.3

```
 CXX      source/core/board/nestopia-NstBoardBmc120in1.o
 CXX      source/fltkui/nestopia-audiomanager.o
 CXX      source/fltkui/nestopia-chtmanager.o
 CXX      source/fltkui/nestopia-inputmanager.o
source/fltkui/inputmanager.cpp:26:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:7364: recipe for target 'source/fltkui/nestopia-inputmanager.o' failed
make: *** [source/fltkui/nestopia-inputmanager.o] Error 1
```

**Comment by rdanbrook** [comment]
@eugene-s-nesdev,
Does the latest commit work for you? std::filesystem is C++17, so I've forced -std=c++17. If this doesn't work, I have another method for cases where it was std::experimental::filesystem.

**Comment by eugene-s-nesdev** [comment]
Almost same compile error (i used "make -j8" at this time)

```
CXX      source/core/board/nestopia-NstBoardBmc120in1.o
  CXX      source/fltkui/nestopia-chtmanager.o
  CXX      source/fltkui/nestopia-audiomanager.o
  CXX      source/fltkui/nestopia-inputmanager.o
  CXX      source/fltkui/nestopia-lodepng.o
source/fltkui/inputmanager.cpp:26:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:7365: recipe for target 'source/fltkui/nestopia-inputmanager.o' failed
make: *** [source/fltkui/nestopia-inputmanager.o] Error 1
```

**Comment by rdanbrook** [comment]
Are you able to give me the version of your compiler and libstdc++? Also, if you change <filesystem> to <experimental/filesystem> do you get a different error?

**Comment by eugene-s-nesdev** [comment]
Sure, i will do it at evening when I get back home

**Comment by eugene-s-nesdev** [comment]
I've compiled (and tested) lastest commit under lubuntu 24.04 (VirtualBox), so it works good.
Regarding old Mint 19, which is installed at my old i7-2600k it has:
```
libstdc++6 (8.4.0-1ubuntu1~18.04)
libstdc++6:i386 (8.4.0-1ubuntu1~18.04)
libstdc++-7-dev (7.5.0-3ubuntu1~18.04)
libstdc++-8-dev (8.4.0-1ubuntu1~18.04)
g++ (4:7.4.0-1ubuntu2.3)
g++-7 (7.5.0-3ubuntu1~18.04)
```
don't worry about it

**Comment by rdanbrook** [comment]
Sounds good, I'll consider this issue complete then.
