### ISSUE TITLE
guide for building the executable and gui for windows

### ISSUE THREAD

**Issue by artynet** [0ldsk00l/nestopia#204]
Hello @rdanbrook ,

would you mind posting a simple guide to build the binaries for windows including its GUI ? Some time ago I build the main executable with a minGW environment on a windows machine and put it in place of the stable (v1.47) of the but it didn't run.....

thanks in advance, Arturo

**Comment by rdanbrook** [comment]
Do you mean the cross-platform port or the legacy win32 port?

**Comment by artynet** [comment]
@rdanbrook the **cross-platform port** first of all. Then if you don't mind I'd like to know more about the legacy win32 build as well. Thank you very much in advance !

**Comment by rdanbrook** [comment]
I do it in an MSYS2 environment with the same dependencies as on Linux, minus GTK+. I can post instructions, but I will have to boot up Windows again (ugh, pain) to write them out.

**Comment by eugene-s-nesdev** [comment]
For legacy win32 build you need to unpack nestopia-win32 (https://github.com/rdanbrook)
over main nestopia source. And you can compile it via MSVS 
(Also you need DXSDK. Sure you added DXSDK includes and libs to MSVS project paths)

@Rdanbrook, seems lastest multiplatform source requires libepoxy-dev, can you update
README.unix ?
