### ISSUE TITLE
Add support for Magic Kid GooGoo 

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#218]
Would it be possible to get support for the recently dumped famicom game Magic Kid GooGoo? I reached out to dragon2snow (who has it working in nestopia already) but he he will not share how to get it working. 

http://forums.lostlevels.org/viewtopic.php?t=3479&postdays=0&postorder=asc&start=60

**Comment by rdanbrook** [comment]
I'll add it soon.

First I will add it to my own emu, since that codebase makes more sense, then I will port to Nestopia.

Thanks for letting me know about this.

**Comment by joepogo** [comment]
No worries man. One day Dracula II fds conversion and magic kid googoo will run wild har har. :P I figured you would want to know about this one. I believe its the last famicom game that needed to be dumped. Unfortunately at the moment it runs on mapper 190, which is unsupported in nestopia. :/

**Comment by rdanbrook** [comment]
Here are some screenshots of it working on my emulator:
![1](https://cloud.githubusercontent.com/assets/1869094/23098544/6d7ac5e6-f61e-11e6-8c31-26e7390ee181.png)
![2](https://cloud.githubusercontent.com/assets/1869094/23098545/725dbfbe-f61e-11e6-80c4-67516e06bc9c.png)
![3](https://cloud.githubusercontent.com/assets/1869094/23098547/75d4afea-f61e-11e6-98fa-08674265873d.png)

It was easy to implement, now I just need to remind myself how Nestopia's mapper system works.

**Comment by joepogo** [comment]
Sweet! Will it be hard to put into nestopia?

**Comment by joepogo** [comment]
Any luck with this rdanbrook? I know dragon2snow has it working but refuses to share it with us. :/

**Comment by joepogo** [comment]
Hey Rdanbrook, any luck getting this to work on nestopia? I tried adding it myself but was attacked by a can of bushs baked beans and dragon2snow. :/

**Comment by rdanbrook** [comment]
It's a very simple mapper, but when I did try adding it to Nestopia it was not as straightforward as I wanted. Now I am leaving the country for a sabbatical, and will not have time to do it before that, so if someone wants to do a pull request... go right ahead, I still have the ability to accept them.

**Comment by dragon2snow** [comment]
what? I attacked you?
build castles in the air! I'm busy. Who's going to attack you?!!

**Comment by joepogo** [comment]
It's a joke dragon. I was kidding. Can you please help us get this game working in nestopia?

**Comment by joepogo** [comment]
I tried but failed

**Comment by joepogo** [comment]
Any plans to add this when you come back rdanbrook? I have tried for the last time tonight. LOL. I need to catch dragon2snow on a good day. Can we chat dragon2snow on messenger soon?

**Comment by joepogo** [comment]
Dracula II fds conversion (thanks to perilsensitive) AND waixings Zelda triforce of the gods now working in nestopia! I am working on Magic Kid goo goo too unless you have that one rdanbrook. When i get a chance i will make the commits for zelda and dracula II to my ue fork on here so you can merge them in. 

Also merged in support for Racermate Challenge II. However, i have no clue how to start this game. :)

**Comment by joepogo** [comment]
Magic Kid goo goo, Dracula II fds conversion, and Zelda triforce of the gods now working! I'll be pushing these commits real soon and will send pull requests for all three games. Well, 4 if you count Racermate Challenge II.
