### ISSUE TITLE
Improve mapper 71 to work with Dooly Bravo Land

### ISSUE THREAD

**Issue by koitsu** [0ldsk00l/nestopia#222]
The Korean game Dooly Bravo Land uses mapper 71 (Camerica).  It's functional in FCEUX, but not in NestopiaUE (game locks up shortly after power-on).

Right now I don't have the time to figure out why, but I'm guessing some PRG swapping issue since none of the initial graphics appear and the game is CHR-RAM.  I at least wanted to file an Issue for it.

Game details (ROM is at archive.org): https://gamehistory.org/dooly-bravo-land/

**Comment by kage2051** [comment]
Camerica games run on Nestopia if you change the mapper to 2 (standard UNROM) using the iNES header editor included in it. At Lost Levels forums I posted an alternate version of the ROM that runs on old emulators such as regular Nestopia and VirtuaNES.

**Comment by dragon2snow** [comment]
this rom is mapper 2,not mapper 71,mapper 71 C000-FFFF,not 8000-FFFF

**Comment by dragon2snow** [comment]
Lost Levels forums and https://gamehistory.org/dooly-bravo-land/  The same PRG!!

not mapper 71!

**Comment by koitsu** [comment]
I am told kevtris was the one who dumped the ROM; I'm having a very hard time swallowing that he would get the mapper wrong. Source reference: https://twitter.com/koitsu2009/status/843889919890149376

**Comment by rdanbrook** [comment]
Even kevtris is not infallible. I tend to agree that it is likely he is correct though. I wouldn't mind seeing a picture of the actual board to confirm.

I have spent a lot of time on the road lately, but things are calming down and I should have time to handle this stuff soon.

**Comment by rdanbrook** [comment]
Fixed in the latest revision.
