### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by hugoarpin** [0ldsk00l/nestopia#225]
Nestopia doesn't work under the wayland backend. Many of the applications that I use still only support X, but they're compatible with Xwayland. I don't clearly understand why, but nestopia isn't.

I've try many things on source/unix/video.cpp to make SDL_CreateWindowFrom work under wayland, but no success. Is there a particular reason why this project can't be run under Xwayland? I'd like to help, but I've never done any UI/GTK coding and I'm overwhelmed. I'm on ArchLinux and since Gnome shifted to the wayland backend, nestopia is painful to run.

Anyway is wayland/Xwayland support planned in the near future?
Thanks for your time.

**Comment by rdanbrook** [comment]
Yeah, it's part of the plan for the next release. I will no longer be using SDL_CreateWindowFrom, I will be using GTK+'s OpenGL context widget for windowed mode and SDL for fullscreen mode.

**Comment by hugoarpin** [comment]
Ok, thank you for the info!
I've look at other projects, like the snes9x gtk port and it seems (to my understanding) to work similarly to what you want to implement.
Since this is not really a "bug", but a planned feature, I'm going to close this issue.
Good look and thanks for the emulator.

**Comment by rdanbrook** [comment]
I started working on this over the weekend and got it working, minus timing/syncing issues. Hopefully it will be working bug-free soon.

**Comment by rdanbrook** [comment]
I have Wayland support enabled on the master branch right now, but it is glitchy. Let me know how it goes if you test it.

**Comment by hugoarpin** [comment]
I've got a linker problem with extern gpad_t pad[NUMGAMEPADS] it seems.
Is there a new dependency or am I missing one?

```bash
CMakeFiles/nestopia.dir/source/unix/main.cpp.o: In function `main':
main.cpp:(.text.startup+0x24d): undefined reference to `gtkui_input_config_write()'
main.cpp:(.text.startup+0x254): undefined reference to `gtkui_input_config_read()'
main.cpp:(.text.startup+0x25e): undefined reference to `gtkui_input_set_default()'
CMakeFiles/nestopia.dir/source/unix/gtkui/gtkui.cpp.o: In function `gtkui_create()':
gtkui.cpp:(.text+0x1271): undefined reference to `gtkui_input_process_key(_GtkWidget*, _GdkEventKey*, void*)'
gtkui.cpp:(.text+0x129c): undefined reference to `gtkui_input_process_key(_GtkWidget*, _GdkEventKey*, void*)'
CMakeFiles/nestopia.dir/source/unix/gtkui/gtkui_config.cpp.o: In function `gtkui_config_input_activate(_GtkWidget*, _GtkTreePath*, void*)':
gtkui_config.cpp:(.text+0x269): undefined reference to `gtkui_input_config_item(int, int)'
gtkui_config.cpp:(.text+0x283): undefined reference to `pad'
gtkui_config.cpp:(.text+0x573): undefined reference to `pad'
gtkui_config.cpp:(.text+0x58b): undefined reference to `pad'
gtkui_config.cpp:(.text+0x5a3): undefined reference to `pad'
gtkui_config.cpp:(.text+0x5bb): undefined reference to `pad'
CMakeFiles/nestopia.dir/source/unix/gtkui/gtkui_config.cpp.o:gtkui_config.cpp:(.text+0x5d3): more undefined references to `pad' follow
CMakeFiles/nestopia.dir/source/unix/gtkui/gtkui_config.cpp.o: In function `gtkui_config()':
gtkui_config.cpp:(.text+0x2ce0): undefined reference to `gtkui_input_process_key(_GtkWidget*, _GdkEventKey*, void*)'
gtkui_config.cpp:(.text+0x2d0b): undefined reference to `gtkui_input_process_key(_GtkWidget*, _GdkEventKey*, void*)'
gtkui_config.cpp:(.text+0x2e51): undefined reference to `pad'
gtkui_config.cpp:(.text+0x2e9d): undefined reference to `pad'
gtkui_config.cpp:(.text+0x2eea): undefined reference to `pad'
gtkui_config.cpp:(.text+0x2f38): undefined reference to `pad'
gtkui_config.cpp:(.text+0x2f86): undefined reference to `pad'
CMakeFiles/nestopia.dir/source/unix/gtkui/gtkui_config.cpp.o:gtkui_config.cpp:(.text+0x2fd3): more undefined references to `pad' follow
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nestopia.dir/build.make:7923: nestopia] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/nestopia.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by rdanbrook** [comment]
Whoops, forgot to update the cmake build file. Try again now. I should also note that you'll get a black screen if you don't specify the ROM on the command line when you first open it (will fix later, there are lots of other bugs too).

**Comment by hugoarpin** [comment]
Well it definitively is a good start.
It is running under gnome-shell wayland v3.24.2 (archlinux). Intel GPU.
I did not work under sway (https://github.com/SirCmpwn/sway), but I don't usually run a widnow manager so my setup might be the problem.

Is it running wayland negatively or through Xwayland?
Anyway, thanks I appreciate the work. I'll look at code for curiosity when I have a bit of time.

**Comment by rdanbrook** [comment]
It's running directly on Wayland if GTK+ is. It just uses the GTK+ OpenGL widget now, so in theory it should also work on Windows with the GUI now, but I haven't tested it. Fullscreen does not work for me yet, but I think I know why. It also appears that the OpenGL widget does not work on OS X yet, so OS X will still have to be GUI-less.

**Comment by hugoarpin** [comment]
I've done a bit of testing. Well apart from the obvious issues, the sound, fullscreen, open roms from gui, the gameplay seems to be pretty much intact, which is very good! I'm sure many are unhappy about this gui refactor, but this probably had to be done sooner or later. As a nice bonus, it hasn't crash on me during normal gameplay under wayland!

**Comment by rdanbrook** [comment]
I have started moving the GUI and emulation loops into their own threads, that seems to solve the problems with audio. I have it basically working but need to do it in a way that is clean before I push.

**Comment by hugoarpin** [comment]
The commit causes emulation to run at hyper speed on my machine, time + video + audio.

There is a problem with nestopia + libao on archlinux, I know that a bug has been reported (https://bugs.archlinux.org/task/49831), maybe I'll try to debug where the problem is coming from if I have time, but SDL audio has always run nicely before we started the GUI refactor.

I'll be sure to look at your next commits, I can pretty much understand what you did with the loops from your first commit, slowly getting familiar about how the GUI is implemented.

**Comment by rdanbrook** [comment]
I changed the SDL audio to be similar to what it was in the last release. It seems to work much better now, but syncing with video is still not perfect.

**Comment by hugoarpin** [comment]
Oh yes, now it's much better, very functional!

It's getting closer, still a few segfaults here and there (opening two roms back-to-back from the gui), but great job!

Is there a make command to build with debug flags? I don't even remember how gdb works though, but I'd like to at least give it a try.

**Comment by rdanbrook** [comment]
./configure --enable-debug=yes

I use nemiver, a nice graphical frontend to gdb.

**Comment by hugoarpin** [comment]
I usually build with cmake, I get errors with autotools.

```bash
$ ./configure --enable-debug=yes
configure: WARNING: unrecognized options: --enable-debug
checking whether configure should try to set CXXFLAGS/CPPFLAGS/LDFLAGS... yes
./configure: line 1880: AX_CHECK_ENABLE_DEBUG: command not found
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
./configure: line 2002: AX_COMPILER_VENDOR: command not found
./configure: line 2003: AX_COMPILER_VERSION: command not found
checking for a sed that does not truncate output... /usr/bin/sed
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
./configure: line 2585: syntax error near unexpected token `${cxxflags_test}'
./configure: line 2585: `       AX_APPEND_COMPILE_FLAGS(${cxxflags_test} -Wno-narrowing, CXXFLAGS)'
```

I ran autoreconf -vif to genrate configure. All the AX_* commands seem to cause errors.
Any idea of what's going on? Thanks.

**Comment by hugoarpin** [comment]
Fixed with #241

**Comment by hugoarpin** [comment]
What seems to reliably cause a segfault when opening multiple roms from the GUI is at source/core/NstPpu.cpp:1388, target pointer is NULL.
It doesn't happen on every rom change, but if I keep changing, I eventually get a sefault.

The renderer is way over my head, but do you have any clue of the cause?
Is it trying to draw while the rom is being changed?

**Comment by hugoarpin** [comment]
I missed that v1.48 was out. It seems to works great under wayland, awesome work!!!
Can we close this issue?

**Comment by hugoarpin** [comment]
Whoops never mind, I tested the HEAD version.
Does it works under v1.48? It doesn't seems so.
But it seems to works great on master branch!
