### ISSUE TITLE
SDL audio issue

### ISSUE THREAD

**Issue by eugene-s-nesdev** [0ldsk00l/nestopia#226]
I've just compiled lastest master and here is issues:
https://youtu.be/EHauane-evw (sorry for video/audio desync)

1) SDL audio driver cause sound distortion both on NTSC and PAL modes 
2) PAL/Dendy run at 60FPS instead of 50FPS when SDL audio driver used.
3) libao audio works correct, but 50FPS games have strong tearing, much stronger than old build had *
4) If you run nestopia, then close it without load rom - there are segfault (look at terminal message).

* Old master tarball i tested (10-dec-2016) works good with SDL and had less tearing on 50FPS.
https://github.com/rdanbrook/nestopia/commit/b5f4f5154916143be0e32d3391a59a00412684fb

Xubuntu 16.04 x64 LTS

**Comment by rdanbrook** [comment]
I've started doing a heavy rewrite, so these issues are only temporary. More stuff is about to break too, as I clean up a horrible mess I created when I was not as skilled a programmer as today.

**Comment by rdanbrook** [comment]
Feel free to try it again now, you will likely experience problems but maybe different ones. There may also be a difference between GUI and CLI interfaces.

**Comment by eugene-s-nesdev** [comment]
Today's build cannoi init openGL, so i see black screen only.
Older version was able to init it: OpenGL: 3.2.0 NVIDIA 340.102
Try on your distro/hardware please

**Comment by rdanbrook** [comment]
What message are you getting? If you try to open the program up and then load a ROM you will get a black screen for now. Did you try opening it from the command line with a ROM as the argument?

**Comment by eugene-s-nesdev** [comment]
No, i tried load rom via GUI.

Also, i have another laptop machine without OpenGL 3.2, and i found solution how to run nestopia,
and it really works with 2016 build:

default was:
evgs@asus:~/Emulation/Nestopia$ ./nestopia
0 joystick(s) found:
Could not create glcontext: Could not create GL contextOpenGL: (null)
Database: 2894 items imported from internal DB
Fds: BIOS ROM ok

Solution:
evgs@asus:~/Emulation/Nestopia$ MESA_GL_VERSION_OVERRIDE=4.0 MESA_GLSL_VERSION_OVERRIDE=400 ./nestopia
0 joystick(s) found:
OpenGL: 4.0 (Core Profile) Mesa 11.3.0-devel (git-36d8fed 2016-04-02 trusty-oibaf-ppa)
Database: 2894 items imported from internal DB
Fds: BIOS ROM ok

**Comment by rdanbrook** [comment]
Yeah, the problem is likely that I need to rework how the GL context is created in GTK+ when the program starts without a ROM. Try ./nestopia romname.nes and it should work now though.

**Comment by eugene-s-nesdev** [comment]
Yes, i tried, it works. Now i see picture.
But still no OpenGL information in terminal (OpenGL: 3.2.0 NVIDIA 340.102)

**Comment by rdanbrook** [comment]
Yeah, that information comes from SDL and since I am no longer using that with the GUI, it will not show. There may be another way to grab that info from the GTK+ GL context. There is quite a lot of work to be done.

Are you noticing any difference in how audio performs? I am going to be beefing up the audio because now everything in the GUI mode runs under the GTK+ main loop instead of an SDL-based event loop, so it needs better buffering probably.

**Comment by eugene-s-nesdev** [comment]
SDL audio still have same problems as written on topic start
