### ISSUE TITLE
Support for oversize Mapper 11 (colourdreams).

### ISSUE THREAD

**Issue by mojontwins** [0ldsk00l/nestopia#234]
Hello.

Some HW implementations of Mapper 11 (colourdreams) - for example, INL's, allow up to 16 bits of both PRG + CHR selection, allowing for 16 PRG + 16 CHR (512Kb PRG + 128Kb CHR) carts.

It seems that Nestopia's implementation of Mapper 11 doesn't quite support oversize.

The official mapping register for Mapper 11 boards is CCCCLLPP, where LL were used for lockout defeat. Oversize boards substitute the nowadays useless LL bits for PRG selectors. The mapper register thus becomes CCCCPPPP.

Currently, both fceux and virtuanes seem to support oversize Mapper 11. Could you consider repurposing the LL bits to PP in Nestopia's implementation so INL oversize Colourdreams boards can be implemented? I can provide test ROMs. A new release using this board will be released later this year, as well.

I believe all you have to do is change this line in NstBoard.hpp:

`DISCRETE_74_377 = MakeId< 11, 128, 128, 0, 0, CRM_0, NMT_X, 0 >::ID,`

To this:

`DISCRETE_74_377 = MakeId< 11, 512, 128, 0, 0, CRM_0, NMT_X, 0 >::ID,`

I will try it myself as soon as I can

Thank you.

**Comment by rdanbrook** [comment]
I would love to see some test ROMs for this. I am definitely willing to modify this mapper to make it work correctly. I have also implemented this mapper in the emu I wrote from scratch on the side, so it would be interesting to see how the test roms work in there.

**Comment by mojontwins** [comment]
I can send you the actual game which will be produced physically, but I can't do it publicly yet (I can send you an email). We won't be releasing the ROM for free until the physical edition is ready.

I can also assemble a plain test rom which lets you page in every PRG and CHR and show the results. Give me a couple of days.

Thank you!

**Comment by rdanbrook** [comment]
It looks like whatever this game was might have ended up using a different mapper. I grabbed all the mojontwins homebrew and nothing uses mapper 11.
