### ISSUE TITLE
Nestopia 1.48 windows missing hide cursor option?

### ISSUE THREAD

**Issue by jjfmz42015** [0ldsk00l/nestopia#249]
The changelog for 1.48 win 32 indicates hide mouse pointer option. However I cant seem to find this option.

**Comment by jjfmz42015** [comment]
Is it a command line setting? I really cant find it.

**Comment by rdanbrook** [comment]
I am on sabbatical with no computer right now so I can't give good instructions. I believe I placed the setting in the same dialogue box that contains file associations etc.

**Comment by jjfmz42015** [comment]
ok thanks for the reply. Myself and 4 others can not find the option.

Its missing from the gui. Just a fyi for whenever you get back to nestopia.

**Comment by jjfmz42015** [comment]
Has anyone else reading this found the option?

**Comment by jjfmz42015** [comment]
?

**Comment by rdanbrook** [comment]
The item in the changelog is for the cross-platform release. Nothing has been done to the win32 release in a really long time. I am accepting pull requests, but will not be working on it myself again, as it is unmaintainable.

The best experience on Windows is available through RetroArch. http://libretro.com
