### ISSUE TITLE
Getting a pointer to the system RAM

### ISSUE THREAD

**Issue by leiradel** [0ldsk00l/nestopia#252]
I'm trying to implement achievements in Nestopia when compiled as a libretro core, but I hadn't any luck so far.

To make it work, I need a pointer to the first byte of the emulated system RAM. My code right now looks like this:

```C++
static Api::Emulator emulator; // this is properly initialized before retro_get_memory is called

void *retro_get_memory_data(unsigned id)
{
   if (id == RETRO_MEMORY_SYSTEM_RAM)
   {
      Core::Machine& machine = emulator;
      return machine.cpu.GetRam();
   }

   return 0;
}
```

Is that the correct way to do it?

**Comment by rdanbrook** [comment]
It appears this has been resolved. Feel free to comment if not.
