### ISSUE TITLE
Multiple Input Button Mappings

### ISSUE THREAD

**Issue by Papermanzero** [0ldsk00l/nestopia#257]
Currently the user can only assign one NES button to one keyboard or controller button.
But especially for modern controller (with dpad and stick) it would be convinient to map the NES dpad to the controller dpad in addition to the stick.

**Comment by rdanbrook** [comment]
I agree, this would be a good feature to add. I will work on it when I have the ability again, which means at least 6 weeks from now.

**Comment by Augusto7743** [comment]
Multiple Input Button Mappings will be very good.
For games that need twice LEFT LEFT or RIGHT RIGHT to run is good for digital pad and other games in left analog.
Multiple input for buttons is good for Double Dragon 2 and others.
If that feature is implemented will be available in Nestopia UE Windows binary ?
Thanks and have a nice day.
