### ISSUE TITLE
request: disk system's 2 disks game support

### ISSUE THREAD

**Issue by io3432iooivzs** [0ldsk00l/nestopia#26]
hi, rdanbrook. sorry my poor engligh, i'm not native english speaker.
nestopia git is wonderful work, i'm glad & used to this emulator on linux.

one requetst, disk system's 2 disks game support.
not A-B side flip, means double disks game.
shin-onigashima, famicom-tantei-club, etc

nestopia can A-B side flip, but disk changes not support yet.
nestopia's disk system sound is great, 2 disks not support is disappointing.

**Comment by prataczak** [comment]
Hi, I have NEStopia 1.47 for windows, and I'm trying to get this feature to work but I can't figure it out. What is the proper procedure to switch disks?

**Comment by io3432iooivzs** [comment]
Your question, means difference between  swith disk and flip disk side?
If so true, switch disk means that switch phosical 2 disk's images.
Flip disk side means that change  A-B side in a disk.
Some disk game title released 2 disks.
Usually, that's game's disk image contains 2 disk's images in one disk image.
ok?

**Comment by prataczak** [comment]
Well for example, the 'No Intro' ROMset has a few games named ending with "Disk 1" and "Disk 2."

Bodycon Quest I - Abakareshi Musume Tachi (Japan) (Disk 1) (Unl), and Bodycon Quest I - Abakareshi Musume Tachi (Japan) (Disk 2) (Unl) is one example.

The disks are split into separate files, and as far as I can tell, there's no way to switch files without rebooting the emulation. The game asks for Disk 2 side as soon as you press start on the title screen.

It looks like there are 6 other games that have Disk 1 and Disk 2 split like this.

I did manage to find a non- No Intro set that had Disk 1 and Disk 2 on the same file. But it was very difficult to find.

No Intro is the new standard these days, soon you won't be able to get a hold of these ROMs without them being split.

**Comment by rdanbrook** [comment]
If I can find these split disk images I will add an option to load separate disks from separate files.

**Comment by prataczak** [comment]
Just now noticed your reply, thank you sir. :)
