### ISSUE TITLE
How to translate nestopia?

### ISSUE THREAD

**Issue by lufog** [0ldsk00l/nestopia#261]
I want to translate NestopiaUE into Russian and Ukrainian. How can i do this?

**Comment by rdanbrook** [comment]
First I will need to add internationalisation support. Currently it can't be translated but I'd like to add this because I want a Spanish translation as well.

**Comment by eugene-s-nesdev** [comment]
http://prdownloads.sourceforge.net/nestopia/Nestopia140lng.zip?download
BTW, old translation for win32-legacy actually exists, it may help you
