### ISSUE TITLE
(libretro) Feature request: Build the NstDatabase.xml into the core

### ISSUE THREAD

**Issue by orbea** [0ldsk00l/nestopia#277]
OS: `Slackware64-current`
nestiopia: 5ecea44

Currently `NstDatabase.xml`is required by the libretro core as a "bios" and the user needs to place it in their system/bios directory.

This adds further complication for users (And package maintainers) for using and distributing nestopia. Its fine the standalone version of nestopia to just install it to `/usr/share/nestopia/`, but RetroArch has no such convenience since the system/bios directory needs to be user writable and could be anywhere.

I think the best way to solve this is to build `NstDatabase.xml` into the libretro core so that its always present. Can this be done?

**Comment by rdanbrook** [comment]
I'd love to do it, but there's no way I've come up with that is clean.

**Comment by orbea** [comment]
What are the specific issues with doing this?

**Comment by orbea** [comment]
I know `GLupeN64` (And maybe `mupen64plus-libretro` still does?) created a similar database file in the system/bios directory if it wasn't present so the user did not have to manually supply it. Maybe this is not the ideal method, but its maybe better than the current one? :)

**Comment by rdanbrook** [comment]
The file is huge, and it's XML so the format is really full of a lot of unnecessary padding. It would be better if it were YAML or even JSON, but it's not. And Nestopia has a built in XML parser, so changing it would be another big hassle.

I did successfully link the XML file by converting it to a char array and including it as a header file. It made the resulting binary HUGE though, and I didn't do any performance testing but I imagine it wasn't a super efficient way to read through all that data.

**Comment by orbea** [comment]
Yes, I see how that could be problematic...

An alternate solution would to solve this long standing RetroArch issue and implement it for the system/bios directory too. https://github.com/libretro/RetroArch/issues/3237

That way package maintainers could just provide the file in a system installed path. I'm not sure how that would work for the buildbot yet though.
