### ISSUE TITLE
(Windows) Why some games are so hard to control with a genuine Xbox 360 controller?

### ISSUE THREAD

**Issue by ferdiweb** [0ldsk00l/nestopia#282]
I find it difficult to use this controller in some games with Nestopia, mainly move the player to the left and right is difficult because sometimes it will not move. I've never had this problem with standard controllers like those produced in China (with those, generally it's very commom that it moves alone, without user reaction).

I have calibrated the controller and verified if it's working in the Windows "game controllers" dialog, and it seems to be working properly as the proper "Test" tab showed for me.

Can one day XInput support in Nestopia change this, or are you aware of any other issues with these controls or even with Nestopia itself?

It would be nice to the emulator see this fixed or working better. But thanks anyway for always updating Nestopia, it should be really hard!

**Comment by rdanbrook** [comment]
For any Windows port issues, I am only accepting pull requests and will not be putting effort into this port. It is not part of the long term plan because it is unmaintainable at this point.

If you are a Windows user, the best experience is available through RetroArch: https://www.libretro.com/
