### ISSUE TITLE
latest dev build

### ISSUE THREAD

**Issue by jjfmz42015** [0ldsk00l/nestopia#283]
how would one compile the latest dev build for win32 here?

**Comment by bunglegrind** [comment]
issue #154 
you'll need to include the header files paths in the project.

**Comment by rdanbrook** [comment]
Depends on what you want to build. The cross-platform port can be built on win32 with MSYS2. If you want to build the legacy win32 port you'll need to drop in the sources at https://github.com/0ldsk00l/nestopia-win32 and compile with MSVC++ 2010.
