### ISSUE TITLE
Hide reticle crosshair option for Zapper usage

### ISSUE THREAD

**Issue by gbrandwood** [0ldsk00l/nestopia#284]
Currently when using the mouse to function as a Zapper, e.g. in Duckhunt, you get the reticle/crosshair corresponding with the mouse cursor movement.  It would great if you could toggle this on and off somehow so that if you are playing using a light gun which mimics a mouse cursor (e.g. Aimtrak), it's more authentic when playing Zapper games (i.e., no reticle should be visible).  Thanks for consideration.

**Comment by rdanbrook** [comment]
Shouldn't be hard to do, will likely do it very soon, once I finish the feature I'm currently working on.

**Comment by gbrandwood** [comment]
Excellent.  Thanks

**Comment by rdanbrook** [comment]
Done!

You'll find the option in the "Misc" tab for GTK+ and in the config file for SDL. I refer to the cursor as "special" because in the future there will be more peripherals with their own cursor.
