### ISSUE TITLE
Flatpak: "Couldn't find current GLX or EGL context."

### ISSUE THREAD

**Issue by mrjohnson22** [0ldsk00l/nestopia#285]
The Flatpak version of Nestopia crashes when launching a game. Running it from the command line shows that it fails with this error:

`nestopia: Couldn't find current GLX or EGL context.`

This is the same failure as what's reported here, but for the Flatpak version: https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/mfg0GZqMbv8

My system config is as follows:
- Fedora 28
- Gnome 3 + Xorg
- output of `flatpak run org.freedesktop.GlxInfo | grep string`:
```
server glx vendor string: SGI
server glx version string: 1.4
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.4
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 18.0.4
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

Other Flatpak programs that use OpenGL, such as Dolphin, do work for me.

If this isn't the right place to document problems with the Flatpak version, please let me know where else I should go.

**Comment by rdanbrook** [comment]
I'm not sure who is making a flatpak of this software. It's certainly not me though, and I only distribute as source, except for a win32 binary when I do official releases.

**Comment by mrjohnson22** [comment]
Thanks for the quick reply. The Flatpak version is hosted by Flathub. I'll find out who's packaging it and will report this problem to them instead.

**Comment by rdanbrook** [comment]
You might want to try compiling from source to see if you can reproduce the problem there. It could be something unrelated to the packaging.

**Comment by mrjohnson22** [comment]
I did try that, but it failed with a different error. I'll post a separate bug for it.
