### ISSUE TITLE
[Arabian Dream Sherazaado (J)] Glitch and missing pause screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [0ldsk00l/nestopia#287]
Hi, 

I found 2 problems with the game Arabian Dream Sherazaado (J). 

Glitch on this picture (red circle) : 

![arabian](https://user-images.githubusercontent.com/12481242/41960474-5805cd1e-79df-11e8-92ce-553c2b7eb813.JPG)

After pushing pause, missing screen : 

![arabian1](https://user-images.githubusercontent.com/12481242/41960497-624e89dc-79df-11e8-90b2-6c8bf28802ab.JPG)

**Comment by dragon2snow** [comment]
1st:I think not bug
2rd:select open info screen

**Comment by rdanbrook** [comment]
I confirmed that the game works in the current build of Nestopia and real hardware exactly the same.
