### ISSUE TITLE
Some Innacurate Sounds

### ISSUE THREAD

**Issue by ghost** [0ldsk00l/nestopia#29]
I haven't tested a whole lot of games, but one in particular has some minor sound issues.

Super Mario Bros 3 for instance sounds incorrect when Mario slides his feet while running (when compared to the real hardware). The sound of his feet sliding "skips" and kinda "pops". If you test it vs. the real thing you'll see what I mean. Heck you can test it vs. FCEU or BSNES (using the NES built in). Both of those emulators sound correct with this aspect.

It may be possible that this is not limited to only SMB3, but other games as well that use similar sounds perhaps? I'm not a coder so I wouldn't know.

Anyway, I thought you would like to know about this.

**Comment by rdanbrook** [comment]
It works in my own emulator, but it's hard to untangle the web of templates that is Nestopia. I may take another look at it in the future, since I do have a working APU of my own now and fully understand how it works. Going on sabbatical though, could be awhile.

**Comment by rdanbrook** [comment]
There is still a horrible sound at the end of the slide with that value sometimes. I have it resolved in my own APU so I will maybe run a comparison one day. Won't have time to do that until Christmas. Maybe someone else can figure out the issue in the mean time.

**Comment by rdanbrook** [comment]
This has been fixed in another fork and the fix will be merged.
