### ISSUE TITLE
[Confusion] Built nestopia; not getting a gui when launching

### ISSUE THREAD

**Issue by Joelgp83** [0ldsk00l/nestopia#290]
Hi guys.

I built nestopia on linux mint 19 from the source here (simply clone'd the git), following the instructions from the git's readme.  I must be missing something here, because whatever it builds seems to be the CLI version of it only.  Launching from the desktop (Cinnamon) does nothing, unless I drag a rom onto the icon, then it launches and immediately runs the rom.  Is this by design, or is there special hoops I gotta jump through to build something that launches into nestopia's gui?

The version in the mint repos is only 1.47, so that's why I'm compiling the first place, I'm curious how much has improved since the release that mint has.

**Comment by rdanbrook** [comment]
You'll need to pass --enable-gui to the configure script.
