### ISSUE TITLE
Audio input support

### ISSUE THREAD

**Issue by rzumer** [0ldsk00l/nestopia#295]
As discussed in #210, audio input device support would allow for more natural emulation of the Famicom microphone, and potentially other microphone peripherals.

Focusing on the Famicom microphone, it appears to act as a binary trigger activated based on the noise level. Capturing amplitude levels at every frame and toggling that input based on a threshold seems to be a good first step, based on experiments performed using https://github.com/rzumer/mic2key, but testing response to various noise levels using real hardware would allow further improvements in that model.

SDL supports audio input, so no additional dependency would be needed. A libretro API extension (see https://github.com/libretro/libretro-common/issues/86) could also be used for capture in the libretro build.

**Comment by rdanbrook** [comment]
This is a really old issue, but I sort of like the idea. I'm going to leave it open, and if I ever decide to actively work on this codebase again then maybe I'll add it.
