### ISSUE TITLE
Save states broken

### ISSUE THREAD

**Issue by Bezier89** [0ldsk00l/nestopia#300]
It appears that a recent build of the Nestopia core has broken save state compatibility :(

I have confirmed that save states created with build cb6c9cc fail to load in build bb6a089 (tested both RetroArch 1.7.4 and 1.7.5). Looking through the commits of the past month, I strongly suspect this is the culprit:

https://github.com/0ldsk00l/nestopia/commit/0b1e5ee27c6fbf0428d0f20c1536d9a2a6c4d7a5

I also suspect this was inadvertently broken, given that Nestopia is a fairly mature piece of software. There's also no mention of a breaking change the [changelog](https://github.com/0ldsk00l/nestopia/blob/master/ChangeLog).

**Comment by bbbradsmith** [comment]
That change only affects mapper 31. Are you talking about savestates with mapper 31, or all savestates? If it's all savestates, no, that code can't possibly be the culprit.

**Comment by rdanbrook** [comment]
It's because items were added to the APU. The structure of the data has changed as a result. Keep in mind that if you are not on a tagged release, you can expect the occasional breakages like this, and things will not necessarily be reflected in the changelog.

**Comment by rdanbrook** [comment]
@Bezier89 I may consider reverting the relevant commits if I can find a better way to solve the problem that @lacastri did. This has been a known issue for a very long time. Perhaps you can offer some suggestions. Here are the commits in question:
https://github.com/0ldsk00l/nestopia/commit/cce1f5b3312ecc2a1a57556111926cbf2abf8d3c
https://github.com/0ldsk00l/nestopia/commit/7857bb47cdacbbb9d07f4576143cce16cee8cb3b

Any other ideas are certainly welcome. If I could have a solution that does not break state compatibility between tagged releases, I would definitely prefer that.

**Comment by Bezier89** [comment]
@rdanbrook Thanks. I'll see if I can take a look at the code more closely this weekend. Just brainstorming, is there anything in the save state that could be used to indicate if it's an "old-style" or "new-style" save state? Easiest would be if some sort of "save state version id" was encoded into the save state, but barring that perhaps some magic bytes could be prepended to the beginning of the save state in the new version. Then, when loading, if the magic bytes are detected it strips them and uses the new loading logic, otherwise it uses the old loading logic. Not the most elegant approach, but I believe it would work.

**Comment by rdanbrook** [comment]
That solution is an option, but I'm afraid of introducing overhead into this heavily abstracted codebase. The fix that was done is a perfect example of what kind of thing can happen when you try to solve what should be a simple problem. I wonder if the solution to the audio runahead could be somewhere outside of the state structure. Maybe even some kind of ugly hack in the libretro port (or other platform specific ports) to keep things in sync.

**Comment by bbbradsmith** [comment]
Wait, isn't the savestate system already built to be backward compatible? The new stuff went in a new "DCB" chunk. How does an old save end up getting invalidated by this? In theory it should just load all the old chunks fine.

**Comment by rdanbrook** [comment]
I think the culprit is the code starting at line 1360 of commit cce1f5b. Changes of size of things already existing may have broken it.

**Comment by bbbradsmith** [comment]
Ah, didn't catch that. Yeah, that extra 5 bytes should probably be moved to a new chunk instead? (Unless there's some way to increase chunk size without invalidating them, but maybe there isn't.)

**Comment by lacastri** [comment]
God Slayer (Japan) is a nice test game; throws lots of runahead problems. Although runahead is libretro-only, it can expose bugs in the save/load state system (snes9x had a bunch of them).

I wouldn't know if libretro.cpp can be hacked to workaround, like using custom machine->SaveStateRunahead or something. @Dwedit is the runahead master and maybe could suggest a good alternative.

**Comment by Dwedit** [comment]
I had made the "Runahead Debugger" for Retroarch, which can trigger breakpoints on any inconsistencies in a save state.

The first kind of test is just to test if saving state, loading state, then saving state again produces identical savestates.  Surprisingly, this fails quite often on emulators.

The second kind of test is to compare two instances: One instance where save states are used every frame, and one instance where it never loads state.  You can save state each frame and see if they match.

If you have Visual Studio, or another suitable debugger, and want to hunt down bugs, you can [try out my Debug Runahead fork of RetroArch](/dwedit/RetroArch/tree/debug-runahead-2).

**Comment by rdanbrook** [comment]
I just merged: https://github.com/0ldsk00l/nestopia/pull/301

I tested it, but perhaps more testing wouldn't hurt.

**Comment by rdanbrook** [comment]
I have not heard any complaints in over a month, and my own testing verifies that this is no longer a problem. If anyone notices problems, I will reopen this issue.
