### ISSUE TITLE
how to do compile the executable for windows

### ISSUE THREAD

**Issue by lgczszs** [0ldsk00l/nestopia#310]
msys2 
 CXX      source/core/api/nestopia-NstApiRewinder.o
  CXX      source/core/api/nestopia-NstApiNsf.o
  CXX      source/core/api/nestopia-NstApiFds.o
  CXX      source/core/api/nestopia-NstApiMachine.o
  CXX      source/core/api/nestopia-NstApiDipSwitches.o
  CXX      source/core/api/nestopia-NstApiUser.o
  CXX      source/core/api/nestopia-NstApiBarcodeReader.o
  CXX      source/core/api/nestopia-NstApiInput.o
  CXX      source/core/api/nestopia-NstApiSound.o
  CXX      source/core/nestopia-NstVideoScreen.o
  CXX      source/core/nestopia-NstCheats.o
  CXX      source/core/nestopia-NstHomebrew.o
  CXX      source/core/nestopia-NstZlib.o
<command-line>: error: expected unqualified-id before string constant
make: *** [Makefile:5089：source/core/nestopia-NstZlib.o]**

**Comment by rdanbrook** [comment]
Compiling that build on Windows is still considered alpha, so you'll have to do some leet hacksoring. In this case it seems related to zlib not being in your include path.
