### ISSUE TITLE
Nuke.YKT's VRC7 instruments dump

### ISSUE THREAD

**Issue by eugene-s-nesdev** [0ldsk00l/nestopia#313]
Instruments was dumped by NukeYKT some days ago:

https://github.com/TASVideos/fceux/commit/45dcb3e2426641775e89c6a984481787ffb543ab
https://github.com/bbbradsmith/nsfplay/commit/2541a7f544d625870afcd712416d5228f95f6c61
Rhytms is dumped too, but it unused (VRC7 chip lacks this output):
https://github.com/bbbradsmith/nsfplay/commit/072cb73b779eb49235335486a1be5d269d36cf8f

I guess nestopia same table is here:
https://github.com/0ldsk00l/nestopia/blob/master/source/core/board/NstBoardKonamiVrc7.cpp

Tech Info:
https://freenode.irclog.whitequark.org/~h~yamahasynths/2019-03-15#24228789;
https://siliconpr0n.org/archive/doku.php?id=vendor:yamaha:opl2#ym2413_instruments

**Comment by rdanbrook** [comment]
Just merged a pull request that fixes it.
