### ISSUE TITLE
Can't install nestopia

### ISSUE THREAD

**Issue by Lutty2029** [0ldsk00l/nestopia#315]
Hey, I used `git` to get nestopia, run `autoreconf -vif` then I ran `./configure` but it says this: `./configure: line 2615: syntax error near unexpected token ${cxxflags_test}'`
`./configure: line 2615: 	AX_APPEND_COMPILE_FLAGS(${cxxflags_test} -Wno-narrowing, CXXFLAGS)'`. What do I do?

**Comment by rdanbrook** [comment]
You are missing some autotools-related packages. If I were to guess I would say autoconf-archive if you're using a Debian-based distribution.
