### ISSUE TITLE
(gtk) Nestopia standalone fullscreen toggle issue

### ISSUE THREAD

**Issue by orbea** [0ldsk00l/nestopia#317]
OS: `Slackware64-current`
GPU: `Radeon RX Vega 56`
mesa: https://github.com/mesa3d/mesa/commit/c613861b23312438568a4a77dc48e383d45ef51e
nestopia: https://github.com/0ldsk00l/nestopia/commit/44800c5f6336894a8307cc03a38403dbfda83d29
wm: https://github.com/conformal/spectrwm/commit/f3d7a4d5e8a349908604ea98fd28addf6f6d1c57
gtk: `3.24.8`

With the gtk+3 standalone frontend for nestopia the fullscreen toggle is problematic. Here it will render the content entirely on the left side of the screen and display garbage on the right. The cli version of nestopia does not have this problem where it will center the content and display black bars on the side as expected.

![gtk](https://i.imgur.com/8fEJNfa.png)

**Comment by hugoarpin** [comment]
@rdanbrook
What seems to be causing the fullscreen issue (at least for me) is gtk_window_set_resizable(GTK_WINDOW(gtkwindow), FALSE) inside source/gtkui/gtkui.cpp. It also prevent my window manger ([sway](https://github.com/swaywm/sway)) from maximizing the window resulting in a floating window.

However if I comment gtk_window_set_resizable the drawingarea get really messed up, it will take up the full window (distorting the aspect ratio) and sometimes truncate the bottom the playfield. But if check in gtkui_resize(), I can see that the dimensions send to gtk_widget_set_size_request(drawingarea, rendersize.w, rendersize.h) are valid.

I do not know why, but it is treating the drawingarea as if it were the screen. Even if I try to resize gtkwindow with gtk_widget_set_size_request(gtkwindow, screen.w, screen.h) before resizing the drawingarea, the issue still persists. I know nothing about GTK+, this is pretty much as far as I can get.

Maybe the drawingarea needs to be embedded into another container that will pad the drawingarea with black bars to center it? If I'm not mistaken I think it is embedded right now inside GtkWidget *box. But even if I try to resize the box before resizing the drawingarea, no change. Am I making sense or am I completely off track here?

**Comment by rdanbrook** [comment]
GTK is dead to me now.
