### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by LennnaLee** [0ldsk00l/nestopia#326]
For whatever reason the cursor is like this when I use this ROM, other ROMs work fine.
https://cdn.discordapp.com/attachments/121412914602180608/657863118092763147/IMG_20191221_163238.jpg

**Comment by rdanbrook** [comment]
That is the crosshair for use with zapper games. You'll notice it also with Wild Gunman, Hogan's Alley, and plain old Duck Hunt.

I can't tell what build you're using there, but it looks like you're on Windows. If by some odd chance you're using the cross-platform build on Windows, then you can set disable_cursor_special=0 in the config file. I can't even remember how to turn the crosshair off on the legacy win32 build, but the option is hidden somewhere in those options dialogs.
