### ISSUE TITLE
U should know that retroarch is shitty software bloatwared in everything, why people who make cores cant have retroarch build...

### ISSUE THREAD

**Issue by noiseshaade** [0ldsk00l/nestopia#331]
- hmm

**Comment by rdanbrook** [comment]
Everyone has their own opinions. Having a libretro core has been a great way to expose more people to the emulator core and has resulted in many emulation fixes over time, coming from libretro users. If RetroArch is not your style, there are other options available to use Nestopia, such as the standalone builds, the OpenEmu build if you have a Mac, or libretro frontends such as ludo or GNOME games.
