### ISSUE TITLE
No 16:9 stretch in fullscreen?

### ISSUE THREAD

**Issue by superluigi018** [0ldsk00l/nestopia#332]
Why is it that I can only stretch the games to 16:9 in windowed mode but not fullscreen? When I enter fullscreen it just goes back to 4:3. Is there something that I'm missing?

**Comment by rdanbrook** [comment]
Actually it is a GTK issue that gives you the ability to stretch to 16:9. I could never figure out how to keep the proper aspect ratio with the GTK OpenGL widget. I would have limited it to 4:3 if it were possible, since the NES was not designed for 16:9 screens.
