### ISSUE TITLE
French translation...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [0ldsk00l/nestopia#336]
Hello, 

Here the french translation, if you want to add it to the windows port.

[français.zip](https://github.com/0ldsk00l/nestopia/files/5643166/francais.zip)

**Comment by rdanbrook** [comment]
Merci beaucoup.

Tal vez puedo hacer una traducción en Español en el futuro también!

I'll see about adding this when I get this repository fixed up for easy Windows builds.

**Comment by BenjaminSiskoo** [comment]
Very nice, My spanish is rusty, I can't help you ^^

**Comment by rdanbrook** [comment]
I actually have no idea how to integrate this directly into the build. The .nlg seems to be a build artifact, so is this from an earlier release? I am not really a Windows dev, so this stuff is really foreign to me.

**Comment by BenjaminSiskoo** [comment]
Martin added the file in the archive. I'm not sure if it's possible to add this on github. To translate it, you need a software like resource hacker.

**Comment by rdanbrook** [comment]
@BenjaminSiskoo is that how you made the translation originally, through hacking the English .nlg?

**Comment by BenjaminSiskoo** [comment]
Yup, When I talked with Martin at the beginning, it was the only way to have a translation.

The easy way will be to add a link to the file on the readme.md !!!

**Comment by BenjaminSiskoo** [comment]
With Kronos/Yabause, there is a simple txt file for the translation.

**Comment by Fruity-0** [comment]
Can I somehow translate the "english.nlg" file?
The file appears to be compiled ..  :-/

**Comment by BenjaminSiskoo** [comment]
@Fruity-0 You have to use a software like ressource hacker (ressource editor). Open *.nlg file with.

**Comment by Fruity-0** [comment]
OKAY. I'll check it. 
Very good emulator and I would like to insert linguistic support for different languages (including my native one)

**Comment by Fruity-0** [comment]
ok it works, thanks guys, now I will slowly translate :-)

**Comment by BenjaminSiskoo** [comment]
Great :)

**Comment by Fruity-0** [comment]
Hello everyone. 
I pre-translated the language file and I have a question:
Will there be any more community-made language updates or does it make no sense to post here on GitHub?

**Comment by rdanbrook** [comment]
Fruity-0, thanks for doing that. I'm going to release a win32 build soon, and I would love to include your work. I don't actually know how to integrate it yet but I'll figure it out. Did you just write it into language.rc? If so, maybe I can add it before I do a release build.

**Comment by Fruity-0** [comment]
>Did you just write it into language.rc?

What do you mean ?
My file that I translate is .nlg, not very professional, because of the resource editor. :-/

**Comment by Fruity-0** [comment]
>Did you just write it into language.rc

Do you mean this file?
![Screenshot_1](https://user-images.githubusercontent.com/31104533/111718555-69e54780-885a-11eb-95d0-05753e152f82.jpg)

**Comment by rdanbrook** [comment]
Yeah, that's what I mean. If you can upload that file, I'll try to add it to the next build. Don't know when exactly I'll do the build but it's coming.

**Comment by Fruity-0** [comment]
Ok, I'll check it out ... 
ResourceHacker works differently so I think it will save all original files to ".rc" format and then I will start translating the rest of the source files.

**Comment by Fruity-0** [comment]
Hello.
A little bit of time, but I checked the language files recently. There are only MENU files for now, but I will slowly translate further in my spare time.
[Polish_file_RC.zip](https://github.com/0ldsk00l/nestopia/files/7035112/Polish_file_RC.zip)

**Comment by Fruity-0** [comment]
I attach (practically 99%) the finished translation file. I will do the rest of the corrections while using the program thoroughly.
I don't think I messed up the source files, if so I will make corrections after the feedback.
[polish_RC_update(05-10-2021).zip](https://github.com/0ldsk00l/nestopia/files/7281856/polish_RC_update.05-10-2021.zip)

**Comment by rdanbrook** [comment]
@Fruity-0 very nice work. I've just tried the polish.nlg file and it works great. I'll add it to the source distribution once I figure out how :).

**Comment by Fruity-0** [comment]
During the translation I noticed that additional characters in the syntax from Polish (ą, ę, ć, ś, ź, ż etc.) in the program are misinterpreted, so I had to use alternative letters. For this reason, I am not able to add a translation in another language without knowing it well enough to keep the meaning of the words and sentences. :-/

**Comment by rdanbrook** [comment]
The French and Polish translations are included in the latest release! Sorry it took so long. I'll leave this open in case there are any other issues related to the translations.

**Comment by BenjaminSiskoo** [comment]
No problem, greeat news :)

**Comment by BenjaminSiskoo** [comment]
You could change the copyright to 2023 :) 

![image](https://user-images.githubusercontent.com/12481242/210064451-94961c89-f1bc-430e-9872-9aae9415e709.png)
