### ISSUE TITLE
Misunderstood

### ISSUE THREAD

**Issue by eugene-s-nesdev** [0ldsk00l/nestopia#339]
Hi, Rdanbrook. Sorry for disturb again, but there are misunderstood situation:

Your PPU code already had FHorse patch in NSTPPU.CPP and NSTPPU.H and it works perfect since 2016
3 days ago you made commit from jgemu branch that contains _**older PPU code**_, and it erase FHorse fix that you had. 
So this is regression.

No way to fix it, or revert commit ((https://github.com/0ldsk00l/nestopia/commit/465fce638baa1c5ad92bb3f771973429549f311a)), or revert only that part of PPU code back?

**Comment by rdanbrook** [comment]
For now, if this is an issue for you, feel free to just revert that merge in your own branch. Don't worry, I'm confident that everything will be fine by the time I am ready for a new release tag, and please remember that I just brought this project back so it's volatile for now. I will be closing and locking any issues related to the core in the future, as this project is solely about the standalone builds now.
