### ISSUE TITLE
Can't configure hard/soft reset keys in GTK

### ISSUE THREAD

**Issue by tetron** [0ldsk00l/nestopia#340]
The GTK UI doesn't support configuring the hard  / soft reset keys, and setting the key binding for "reset" in `~/.nestopia/input.conf` has no effect.  It seems that only F12 works for reset, and that only performs a soft reset.

If I have some time over the holidays I'll see if I can make the changes and provide a pull request.

**Comment by rdanbrook** [comment]
Try ~/.nestopia/gtkinput.conf instead and see if that helps you.
I got rid of the SDL-only build, so I will be unifying the config at some point so it is less of a mess. It might be a good time to add a hard reset config item too.
