### ISSUE TITLE
Cannot exit fullsreen

### ISSUE THREAD

**Issue by AndrewRosenthal** [0ldsk00l/nestopia#341]
Upon entering full screen, I now cannot exit fullscreen to play games or load ROMS 

![image](https://user-images.githubusercontent.com/76230514/103468339-19b01c00-4d26-11eb-9108-acf6e03283ff.png)

**Comment by ricardoseriani** [comment]
Try pressing `T` or edit the file `~/.nestopia/nestopia.conf`, search for `fullscreen=1` and change it to `fullscreen=0`

**Comment by jonadem** [comment]
Editing the file `~/.nestopia/nestopia.conf` worked for me (but pressing `T` didn't).

**Comment by rdanbrook** [comment]
No longer relevant after the toolkit change.
