### ISSUE TITLE
XDG basedir

### ISSUE THREAD

**Issue by Svadkos** [0ldsk00l/nestopia#343]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Move config to `XDG_CONFIG_HOME/nestopia` with fallback to `~/.config/nestopia` and `~/.nestopia` can be used for backward compatibility.

To comply with spec better, directories for saves, state, cheats etc can be moved to `XDG_DATA_HOME/nestopia`.

**Comment by rdanbrook** [comment]
Yeah, I am open to doing this. It's what all the cool kids are doing.

**Comment by rdanbrook** [comment]
It's done. I am not doing backwards compatibility because I am going to be doing more radical breaking changes before the next tag anyway.
