### ISSUE TITLE
new graphic for snes controller

### ISSUE THREAD

**Issue by netpipe** [0ldsk00l/nestopia#345]
https://github.com/0ldsk00l/nestopia/blob/master/icons/svg/nespad.svg change the graphic on the controller to avoid patent infringement

says something about 3 grey bars start and select  wrote in red and the nintendo trademark

**Comment by netpipe** [comment]
change the writing to blue and remove one grey bar and remove nintendo logo

**Comment by netpipe** [comment]
https://github.com/punesemu/puNES/blob/master/src/gui/designer/pics/Nes_controller.svg i got them to change this one already

**Comment by rdanbrook** [comment]
Thanks for pointing this out. It really was a potential problem. Now the controller looks like the aftermarket knockoffs that cost $2 on eBay instead of the OEM controller. I think that should be good enough.

**Comment by netpipe** [comment]
![nespad](https://user-images.githubusercontent.com/172564/109592176-14741100-7acc-11eb-8783-01a9be6022c6.jpg)

**Comment by netpipe** [comment]
no one said the ebay controllers are even good its just they had to look closer than what we need. please update this graphic or pick your own colors in gimp and using color levels.

**Comment by rdanbrook** [comment]
https://trademark.trademarkia.com/nintendo-select-start-b-a-86565763.html
No reasonable person would consider the image that is now in the repo as infringing. I believe the removal of the Nintendo label is probably enough, but changing the colours removes all doubt, and gives me an excuse to match the colour scheme up with the icon and website.
