### ISSUE TITLE
Buttons with strange behavior in some ROMs

### ISSUE THREAD

**Issue by SilverKnight-Z** [0ldsk00l/nestopia#350]
First of all, I'm using Nestopia UE 1.50 32-bit on Windows 7 Starter SP1 32-bit

I configured the buttons as follows:
B: X
A: C
Select: Space bar
Start: Enter
Autofire B: S
Autofire A: D

However, in a couple of roms there are buttons that don't behave as they should, for example:

In 'Contra Force (USA)', 'Autofire B' behaves as if you press 'Start'.

In 'Mickey Mousecapade (USA)', 'A' behaves as if pressing 'A+B'; and 'B' behaves as if pressing 'B+Left Arrow'.

**Comment by rdanbrook** [comment]
I was unable to reproduce this problem with the old version and the latest release. Delete your config and try again, and maybe you'll have better luck.
