### ISSUE TITLE
[Feature Request] Borderless Window Mode

### ISSUE THREAD

**Issue by properchopsticks** [0ldsk00l/nestopia#352]
hi,

currently nestopia only allows dedicated full screen mode. is it possible in the future to implement borderless window mode as well?

thanks

**Comment by rdanbrook** [comment]
I don't actually know if it's possible with the present win32 build, which uses really old libraries. I think that's what you're referring to because the FLTK build does do it this way. I'll accept a pull request that allows this if anyone else can figure it out.

**Comment by properchopsticks** [comment]
got it, thanks for the feedback. 😀 and also i wanted to mention, retroarch also has a nestopia core and it's also able to run in borderless window, i don't know if it's possible to copy the code from there but i think it could be a good starting point.
