### ISSUE TITLE
[1.51.0] build error on undeclared identifier 'GL_TEXTURE_3D_EXT'

### ISSUE THREAD

**Issue by cho-m** [0ldsk00l/nestopia#353]
As reference, this was seen on trying to add v1.51.0 to Homebrew: https://github.com/Homebrew/homebrew-core/pull/78170

The exact error seen is:
```make
source/fltkui/video.cpp:81:12: error: use of undeclared identifier 'GL_TEXTURE_3D_EXT'
        glDisable(GL_TEXTURE_3D_EXT);
                  ^
1 error generated.
make: *** [source/fltkui/nestopia-video.o] Error 1
make: *** Waiting for unfinished jobs....
```

Which is occurring here:
https://github.com/0ldsk00l/nestopia/blob/1c1989ae0667fd2ab935f7ad5cbadb8fe2299cd0/source/fltkui/video.cpp#L81

---

On side note, if I try deleting the line, the build fails at a different line:
```make
source/fltkui/fltkui.cpp:328:2: error: unknown type name 'Fl_Button'
        Fl_Button close(360, 400, 80, 24, "&Close");
        ^
1 error generated.
make: *** [source/fltkui/nestopia-fltkui.o] Error 1
make: *** Waiting for unfinished jobs....
```

---

Then if I add `#include <FL/Fl_Button.H>` to source/fltkui/fltkui.cpp the build succeeds, but the test we use for version output fails:
```
Error: nestopia-ue: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /Nestopia UE 1.51.0$/ to match "Nestopia UE vx.xx\n".
```

Manually running the command, I get:
```console
❯ nestopia --version
Failed to read config file /Users/cho-m/.config/nestopia/nestopia.conf: Using defaults.
Nestopia UE vx.xx
```

**Comment by rdanbrook** [comment]
Thanks for letting me know, the latest commit should fix this.

I don't have the resources to test builds on macOS anymore, which is why I removed it from the list of supported OSes. It's nice to know it does somewhat build still, and I'm accepting any pull requests that will allow it to keep working.

**Comment by cho-m** [comment]
Thanks for quick fix. I'll close this now as I see local build is successful and at least a quick test with NES ROM seems to work.
