### ISSUE TITLE
[Feature Request / win32 build] restore classic icon

### ISSUE THREAD

**Issue by eugene-s-nesdev** [0ldsk00l/nestopia#354]
I know this is going to sound foolish...
but i still sure that classic 1.40 default icon is much more good-looking and suitable than zombie's hand:

![test01](https://user-images.githubusercontent.com/13199529/122120538-3901b800-ce33-11eb-8b6f-73ee8ee6a71e.png)

![test](https://user-images.githubusercontent.com/13199529/122119934-7a459800-ce32-11eb-99e4-8d4d93178341.png)

**Comment by rdanbrook** [comment]
This has been the icon for close to a decade, and it's a good way to tell this is not the original project. It's a tribute to Bloodlust Software, so it needs to be ugly and obnoxious.
