### ISSUE TITLE
Allow to load patches manually

### ISSUE THREAD

**Issue by lwcorp** [0ldsk00l/nestopia#358]
If you unselect **Auto patch** there seems to be no way to load the patches.

This is unlike cheats which can be triggered manually via `Options=>Cheats`

Expected behavior:
Please add a `Options=>Patches` menu that will allow to trigger patches manually

Either that or remove the **Auto patch** option as it's not logical.

![image](https://user-images.githubusercontent.com/1773306/134769384-e29287ae-267e-48c2-8527-73872689d5b9.png)

**Comment by rdanbrook** [comment]
Closing because this is addressed in another issue.
