### ISSUE TITLE
Performance and Input lag issues on Linux

### ISSUE THREAD

**Issue by IoMarz** [0ldsk00l/nestopia#363]
OS: Debian 11 GNU/Linux
I have compiled Nestopia 1.51.1 with the instructions provided in the readme.
However compared to the windows version, the linux version has worse input delay & performance. Is this a known issue? I have not found a solution anywhere for this.
PS. I have tried the windows version with multiple versions of wine and still experiencing input lag.

**Comment by rdanbrook** [comment]
What desktop and/or compositor are you using?

There shouldn't be any significant difference. The win32 build does eat slightly less CPU but it should not make a noticeable difference on any computer made in the last 15 years.

So are you comparing the FLTK build to the win32 build running within WINE, or the win32 build running on bare metal Windows? How much of a difference are you noticing?

**Comment by IoMarz** [comment]
All of the default settings in the FLTK build and win32.

> So are you comparing the FLTK build to the win32 build running within WINE, or the win32 build running on bare metal Windows? How much of a difference are you noticing?
I'm comparing all 3. I'm not sure exactly how much of a difference there is in performance, but for input lag its pretty noticeable for me.

**Comment by rdanbrook** [comment]
Thanks for those details. Are you using a non-60Hz monitor by any chance? What about your audio, do you use pulseaudio, pipewire, or any other intermediary between you and ALSA? And also, are you using a keyboard or a USB gamepad?

**Comment by IoMarz** [comment]
Im using a 1ms 144hz monitor, pulseaudio, and a razor blackwidow keyboard

**Comment by rdanbrook** [comment]
I think it might be related to the high refresh monitor. It is only polling input when an emulated frame executes, and the way I am doing timing on non-60Hz monitors is through the size of the sound buffer. I probably have to rewrite this and hope it works :).

**Comment by rdanbrook** [comment]
Okay, the frame timing is rewritten, hopefully this fixes it. Let me know if you still have problems. By the way, I think it will probably be smoother at 120Hz than 144Hz since 120 is a multiple of 60.
