### ISSUE TITLE
Zelda - The Legend of Link patched incorrectly

### ISSUE THREAD

**Issue by xuefer** [0ldsk00l/nestopia#364]
patch is "Zelda - The Legend of Link (v3-12-20).ips" from https://www.romhacking.net/hacks/2136/
CRC32 of ips file is D4DBC71D
SHA-1 of original rom is DAB79C84934F9AA5DB4E7DAD390E5D0C12443FA2
when incorrectly patched by nestopia, tiles is wrong. but patch using "Lunar IPS.exe" works just fine

![Zelda - The Legend of Link_002](https://user-images.githubusercontent.com/1741312/147883763-f411563e-f43d-4a47-bf0a-b9043af58cd6.png)

![Zelda - The Legend of Link_001](https://user-images.githubusercontent.com/1741312/147883798-50d659a5-ba01-46cf-951b-23905ce3bae9.png)

**Comment by rdanbrook** [comment]
This project is now only about maintenance of a GUI built around the Nestopia emulator core. Nestopia JG is the upstream provider of the emulator core, so the best place to post this kind of issue is here: https://gitlab.com/jgemu/nestopia
