### ISSUE TITLE
MMC3 Error

### ISSUE THREAD

**Issue by MediaMaquina** [0ldsk00l/nestopia#365]
![ff3e_001](https://user-images.githubusercontent.com/8179611/149658537-e76f7bf5-1b86-42d8-bff1-ee2a36c0b018.png)

Hello! I got this explanation from the readme:

> "In order to make the translation as high-quality as possible, the patch takes the approach of Dragon Quest/Warrior IV and expands the ROM size to 1MByte; unfortunately, some emulators don't support this type of ROM correctly.  When the ROM starts, it checks whether the emulator can handle 1MB ROMs, and displays an error screen if not.  If you see the error"

This is the patch that caused it https://www.romhacking.net/translations/1590/

Any help is appreciated.

**Comment by dragon2snow** [comment]
mmc3 max PRG 3F
https://wiki.nesdev.org/w/index.php?title=MMC3

using mapper 224

**Comment by carmiker** [comment]
This should not be switched to use Mapper 224. Though that may appear to work, the correct solution is to implement support for an MMC3 variant that can map more memory. This hack does not switch any subtle behaviours from standard MMC3 to an MMC3 variant that exists in the real world, so it is technically a fantasy mapper.

My implementation was done yesterday:
https://gitlab.com/jgemu/nestopia/-/blob/master/src/board/NstBoardUnlMmc3BigPrgRom.cpp

This is the correct solution and will work reliably.

**Comment by rdanbrook** [comment]
This change has now been merged into the master branch.
