### ISSUE TITLE
Castlevania (USA) (Rev 1) using cheat the wrong way

### ISSUE THREAD

**Issue by Cibomatto2002** [0ldsk00l/nestopia#368]
If I put in this cheat SZSVLYSE I get Infinite Energy with is right but it also makes my hearts go up witch is not right. I tried on all emulators that RetroArch has and netopia is the only one that does this.

![2](https://user-images.githubusercontent.com/21169038/152689340-2764b678-70f9-46ca-800d-e155d664786d.jpg)

**Comment by dragon2snow** [comment]
this gamegeine SZSVLYSE is bug!

**Comment by Cibomatto2002** [comment]
That's interesting. Wonder how other emulators make it work like Mesen and fceumm? No one said anything about it here.

https://gamehacking.org/game/29202

**Comment by dragon2snow** [comment]
Fceux 2.4.0，Mesen 0.9.9 Same effect

**Comment by Cibomatto2002** [comment]
You was right it doesn't happen as often sorry I wasted your time i never notice it before.
