### ISSUE TITLE
Error helpme

### ISSUE THREAD

**Issue by jose89fcb** [0ldsk00l/nestopia#369]
Hello very good, I am trying to compile the emulator but I have many errors, could someone help me

Here I leave a capture
<img src="https://i.imgur.com/k4fARmP.png">

thank you

**Comment by rdanbrook** [comment]
You've got some pretty serious errors there. I'm not sure what you're doing wrong, can you give me more details on your toolchain?

**Comment by dragon2snow** [comment]
1.DirectX SDK
2.Original Netopia, does not support X64 MFC compilation
