### ISSUE TITLE
[Regression Found] - Unoffical Instruction Timings are Off/Wrong 

### ISSUE THREAD

**Issue by Zenjir0** [0ldsk00l/nestopia#374]
## Description
I was running the latest version through a gauntlet of benchmarks and found that in version 1.50-win32 passes blargg's [instr_timing](https://github.com/christopherpow/nes-test-roms) tests, but the most recent 1.51.1 fails the first test with the following message:

Older Version (1.50-win32)
![image](https://user-images.githubusercontent.com/27794756/162649073-8ad9e66b-fc92-44a9-9461-6cae8ad3428c.png)

Newer Version (1.51.1-win32)
![image](https://user-images.githubusercontent.com/27794756/162649104-6a612688-170b-4845-b488-08b544e1260c.png)

### Expected behavior
Should pass like the first image. 

### Actual behavior
Fails stating that Unofficial Instructions 9C and 9E was 4, and should be 5.

### Steps to reproduce the bug
1. Start Nestopia-UE version 1.50.0 and run the "[1-instr_timing.nes](https://github.com/christopherpow/nes-test-roms/tree/master/instr_timing/rom_singles)" test rom. 
2. Repeat Step 1 with version 1.51.1

### Bisect Results
This issue started with the latest version. I have only tested version 1.49, 1.50, 1.51, and 1.51.1
Only those after 1.50 are failing the test.

### Environment information

- OS: Windows 10 21H2 64bit

**Comment by carmiker** [comment]
@Zenjir0, this has been fixed in my upstream repository. It should be fixed here the next time a sync is done. I am busy with Neo Geo emulation right now, but I may work on the Nestopia core again soon to tie up another point release that the downstream projects can sync with.

**Comment by Zenjir0** [comment]
@carmiker No worries. I just wanted to report my finding, just in case. I just like to test emulators in my spare time, and want to contribute to projects as best I can.

**Comment by Zenjir0** [comment]
Per comments above issue is known and will be fixed in a future release.
