### ISSUE TITLE
Dendy Mode Should Not Use Same PAL Pitch

### ISSUE THREAD

**Issue by ghost** [0ldsk00l/nestopia#375]
Dendy Uses Silmar NTSC Pitch With 50Hz.

NTSC
![NTSC](https://user-images.githubusercontent.com/103879023/163720507-7f678fe9-6f65-4645-8a7a-a0ace0129bfc.png)

PAL
![PAL](https://user-images.githubusercontent.com/103879023/163720512-2bab9f4d-cd11-474b-8314-b9d6592e8c40.png)

Dendy
![DENDY](https://user-images.githubusercontent.com/103879023/163720515-0ef6853e-ef02-467d-abd0-d5b2e0a9bda5.png)

**Comment by rdanbrook** [comment]
I can't really make sense of this one.
