### ISSUE TITLE
VT03 Games are not working on Nestopia UE

### ISSUE THREAD

**Issue by CraftFan24** [0ldsk00l/nestopia#377]
I found VT03 NES Games but it's not working on Nestopia UE. VT03 is 16-bit NES Famiclone graphics game but it's not working on Nestopia UE, FCEUX, Mesen, QuickNES, ViurtalNES and it says "failed to load game".

VT03 Games:
`Battlefield (Unl) (VT03).nes`

`Burrow (Unl) (VT03).nes`

`Discus Put (Unl) (VT03).nes`

`Dune War (Unl) (VT03).nes`

`Enchanter (Unl) (VT03).nes`

`Ghost Palace (Unl) (VT03).nes`

`Labyrinth (v2007SR01492) (Unl) (VT03).nes`

`Lucky Time (Unl) (VT03).nes`

`Memory Test (Unl) (VT03).nes`

`Shot Put (Unl) (VT03).nes`

`Silent Hunter (Unl) (VT03).nes`

`Sniper (Unl) (VT03).nes`

`Star (Unl) (VT03).nes`

`Star Attack (Unl) (VT03).nes`

`Sur LC (Unl) (VT03).nes`

Download VT03 Games: https://drive.google.com/file/d/1GQJ_ftpKWLbmIgY1L_iZt3YRvFxpZ8Qe/view?usp=drivesdk

Is it possible to add VT03 Support, 16-bit support.

**Comment by rdanbrook** [comment]
This project is now only about maintenance of a GUI built around the Nestopia emulator core. Nestopia JG is the upstream provider of the emulator core, so the best place to post this kind of issue is here: https://gitlab.com/jgemu/nestopia
