### ISSUE TITLE
Dendy mode should NOT be same PAL mode

### ISSUE THREAD

**Issue by ghost** [0ldsk00l/nestopia#379]
On Nestopia: why Dendy mode uses Same PAL mode but it's incorrect. Dendy mode uses difference than PAL mode. It's fine on FCEUX

PAL:

Cycles/line: 106.3

Lines/frame: 313

NMI scanline: 241

TV system: PAL (50Hz)

Frame rate: 49.85

CPU speed: 1.661

---
**Dendy:** (correct)

**Cycles/line: 113.4**

**Lines/frame: 313**

**NMI scanline: 291**

**TV system: PAL (50Hz)**

**Frame rate: 49.85**

**CPU speed: 1.771**

---
NTSC/Famicom:

Cycles/line: 113.4

Lines/frame: 262

NMI scanline: 241

TV system: NTSC (60Hz)

Frame rate: 60.10

CPU speed: 1.787

---
PAL Mode:

https://user-images.githubusercontent.com/105673473/169589434-4dedd219-797b-4315-a4e7-1e49ea9345f6.mp4

---
Dendy Mode (correct):

https://user-images.githubusercontent.com/105673473/169589575-e0bd7bc5-7dae-48fb-9d8f-d70605d9dccf.mp4

It's with **cycle/lines,** **NMI scanline,** **CPU speed**

**Comment by carmiker** [comment]
Hello there @Squidward22. I rewrote the portions of the emulator core that handle Dendy mode, and I did test to make sure it was done correctly. Would you be able to supply more details, and perhaps describe how you are testing this? I am using `oc.nes` and `240pee.nes`.

**Comment by rdanbrook** [comment]
I can't make any sense of this, and the user has deleted their account. Closing!
