### ISSUE TITLE
nestopia_libretro doesn't save input_libretro_device

### ISSUE THREAD

**Issue by kaylh** [0ldsk00l/nestopia#380]
Hello,

I seems that nestopia libretro core doesn't save and load values at `input_libretro_device_*` in `retroarch.cfg`.

e.g If I want to use the zapper as emulated device, it works when I select it in the menu, but the next time when I run retroarch with nestopia, it always revert back to auto.

All others settings are saved, but not those related to inputs.

I use retroarch 1.10.3 Windows 64bit with the latest build of nestopia_libretro available on the buildbot.

**Comment by rdanbrook** [comment]
Sorry for this super late response. The libretro core is not developed here, it is developed over here: https://github.com/libretro/nestopia

You may also want to try doing the same thing with another emulator core. I'm not sure this is a core issue or something to do with how settings work in RetroArch.
