### ISSUE TITLE
Support for DreamGEAR 75-in-1 & DreamGEAR 101-in-1 mapper

### ISSUE THREAD

**Issue by ghost** [0ldsk00l/nestopia#384]
I test DreamGEAR 75-in-1 & DreamGEAR 101-in-1 on Nestopia UE, It doesn't work and it says "Unsupported Mapper"

DreamGEAR 75-in-1
![DreamGEAR 75-in-1 (Unl)  U ! 000](https://user-images.githubusercontent.com/110498392/182845815-efd6b9a2-15e0-492e-a384-2c60d062c4cf.png)
![DreamGEAR 75-in-1 (Unl)  U ! 001](https://user-images.githubusercontent.com/110498392/182845825-57ecc588-0813-46a4-9549-7846c489554e.png)

DreamGEAR 101-in-1
![DreamGEAR 101-in-1 (Unl)  U ! 000](https://user-images.githubusercontent.com/110498392/182845834-6cb0c8b0-8aa4-4efb-95ed-4227fdbbc7c3.png)
![DreamGEAR 101-in-1 (Unl)  U ! 001](https://user-images.githubusercontent.com/110498392/182845846-b729cafe-447e-436f-a77a-0c1926619693.png)

Download DreamGEAR 75-in-1 & DreamGEAR 101-in-1 to test on Nestopia UE https://drive.google.com/file/d/10G096qVIXcIpZkCk9mR81anKbrT2961h/view?usp=drivesdk

**Comment by carmiker** [comment]
These are actually UNL-ONEBUS, or VT02 games (NES 2.0 Mapper 256). Nestopia does not support VTxx systems at this time, and adding support is a rather complex task, given the way this codebase was written. I will keep note of this in case I ever want to take on a major challenge that presents me with little reward :).
