### ISSUE TITLE
Add Horizontal Overscan optional

### ISSUE THREAD

**Issue by MineCreeper9898** [0ldsk00l/nestopia#388]
It uses on real NES hardware. Horizontal overscan shows empty areas in left & right.

![Horizontal Overscan](https://user-images.githubusercontent.com/111442545/187459951-11a1ee94-9eeb-4887-8f91-11e1bc2763cf.png)

**Comment by rdanbrook** [comment]
The best way to achieve this effect is to use blargg's NTSC filter with the RGB setting. You'll see the horizontal overscan on the edges, and it is going to be more similar to a real TV than the screenshot above. I've never seen that much horizontal overscan on a real TV.
