### ISSUE TITLE
DEFAULT_PALETTE = PaletteType::PALETTE_YUV conflicts with wingdi.h

### ISSUE THREAD

**Issue by slajerek** [0ldsk00l/nestopia#390]
Hi!

When I try to compile my own modified NestopiaUE source within RetroDebugger: https://github.com/slajerek/RetroDebugger
I hit the error that DEFAULT_PALETTE definition in enum from NstVideoRenderer.hpp conflicts with Windows' wingdi.h definition of the same name (in wingdi.h #define DEFAULT_PALETTE 15). It is enough just to change the enum name from DEFAULT_PALETTE to for example NES_DEFAULT_PALETTE. It would be cool to change that in your sources to avoid the conflict. 

Note, I've integrated NestopiaUE 1.51.1 to RetroDebugger and it works well! Thanks!

**Comment by rdanbrook** [comment]
Hey, that is a very cool project you have there. Once I have a bit more free time I'll play around with it a bit.

For something like this, I recommend sending it upstream. This is now just a downstream project to maintain a working GUI, but the emulator is core is developed over here: https://gitlab.com/jgemu/nestopia

There is actually a bunch of stuff in the upstream repo that I haven't integrated into Nestopia UE yet... maybe I'll do that over the weekend.

**Comment by slajerek** [comment]
Great, thanks for the quick answer. I'll post that to the other repository.

**Comment by carmiker** [comment]
This has now been fixed upstream.

**Comment by slajerek** [comment]
Great, thanks! Note, I pushed changes to debugger with merged NestopiaUE yesterday :)
