### ISSUE TITLE
Quit hotkey for joysticks

### ISSUE THREAD

**Issue by Lutzx** [0ldsk00l/nestopia#394]
Would it be possible to add a quit hotkey configurable for joysticks in input.conf? Kinda related but Alt+Q doesn't seem to work after using -f or --fullscreen on FLTK

**Comment by Ka-hu** [comment]
I think it would be nice to enable any command to be mapped to joystick/gamepad buttons. For example, I'd like to map the save/load state to to my X360 gamepad (e.g.: to LB and RB buttons).

**Comment by verhovensky** [comment]
+1

**Comment by rdanbrook** [comment]
It's done!
