### ISSUE TITLE
Add support for mapper 354

### ISSUE THREAD

**Issue by nb5846** [0ldsk00l/nestopia#398]
Is it possible to add support for the mapper 354 (submapper 0 and 1) in the next release ?

Wiki : https://www.nesdev.org/wiki/NES_2.0_Mapper_354
A NES rom with mapper 354 submapper 1 : https://forums.nesdev.org/download/file.php?id=23765

Careful for the game B-Wings (Game 71 and 701 of the NES rom above).
It needs CHR-RAM protect.

**Comment by carmiker** [comment]
Oh, it is very possible. Perhaps even likely.

**Comment by nb5846** [comment]
Careful for a potentially bug with the game B-Wings :
`71 - B WING
`
`701 - B WING I
`

**Comment by carmiker** [comment]
This will be included in the next tagged release.
