### ISSUE TITLE
Mapper 227 : Bug with B-Wings

### ISSUE THREAD

**Issue by nb5846** [0ldsk00l/nestopia#403]
For this rom that uses the mapper 227 : [romMulticart.nes](https://forums.nesdev.org/download/file.php?mode=view&id=24234)
(md5sum => fcd14358d45211b5887b69be3405a1be)

It seems that there is a bug with the game B-Wings :
Music ok but blue screen and no gamepad

It's probably necessary to add CHR RAM write-protection for fixing this bug.

Bug for the entry in the menu :
16 - B-Wings
...

I try this multicart dump with Nestopia UE 1.50.
This B-Wings entry seems to work nearly correctly with libretro-fceumm (retroarch).

Could someone correct this bug ?

**Comment by carmiker** [comment]
I'm unable to reproduce this, as my B-Wings dump is mapper 185. Are you sure you're using a good dump?

**Comment by nb5846** [comment]
Yes, I use a good dump with Nestopia UE 1.50, and I have a blue screen for this game.
B-Wings seems to work nearly correctly with libretro-fceumm (retroarch).
Have you test with this dump : [dump.nes](https://forums.nesdev.org/download/file.php?id=24213) ?

**Comment by carmiker** [comment]
That file does not seem to exist anymore.

**Comment by nb5846** [comment]
?
It has just been dumped.
md5sum 120in1-contra-1992.nes
bb8b6c6dd09ae5aee4cb642e5bd57368  120in1-contra-1992.nes

**Comment by nb5846** [comment]
Sorry, it's a permission problem.

Is it ok with that link :
[rom.nes](https://forums.nesdev.org/download/file.php?id=24224)

**Comment by carmiker** [comment]
https://www.nesdev.org/wiki/INES_Mapper_227
It appears there has been a submapper assigned unofficially for this, in order to denote CHR RAM write protection. It should be trivial to add, but this is likely going to require a database entry.

**Comment by nb5846** [comment]
I have corrected the header of the dumpfile in my first message and set it to the submapper 1 as described in the wiki.

**Comment by carmiker** [comment]
![1679979853-732](https://user-images.githubusercontent.com/54966017/228133628-4f6a09b9-0be1-441d-a596-70eae122bd8e.png)
I've gotten it working, but I will need to clean up some of the code to handle the difference between submapper 0 and 1 correctly.

**Comment by carmiker** [comment]
This will be available in a tagged release of 1.52.1 or 1.53.0, depending on how many other things are added before the release. You can use it now by building Nestopia JG, which I have made quite easy for anyone with a development environment to do.

**Comment by nb5846** [comment]
OK. Thank you very much to you.
