### ISSUE TITLE
Green Screen of Doom in Getsu Fuma Den (Nebulous Translation 1.01)

### ISSUE THREAD

**Issue by TsukiZero** [0ldsk00l/nestopia#412]
I don't know the cause, might be something to look into.
Header settings:
![image](https://github.com/0ldsk00l/nestopia/assets/78157224/6365ca2b-1d77-49ff-b7cb-09d2a697ee63)

(Patched) ROM hashes:
CRC32: DAD72CC9
MD5: CEF22723BE6F366477C6B24F5A9FC30E
SHA-1: 5E74648BEC226B0C41081BB5CC437D6B3463C15E

At least it no longer spouts the unsupported mapper nonsense.

**Comment by dragon2snow** [comment]
ADD xml to database,Change the values of CRC and SHA1 to your ROM value,
` <game>
        <cartridge system="Famicom" dump="ok" crc="49123146" sha1="D43D51E63AB14F5DEB38FD2C393E7550705675B4">
            <board type="KONAMI-VRC-2" mapper="23">
                <prg size="128k" />
                <chr size="128k" />
                <chip type="Konami VRC II">
                    <pin number="3" function="PRG A1" />
                    <pin number="4" function="PRG A0" />
                    <pin number="21" function="CHR A10" />
                    <pin number="22" function="CHR A16" />
                    <pin number="23" function="CHR A11" />
                    <pin number="24" function="CHR A13" />
                    <pin number="25" function="CHR A14" />
                    <pin number="26" function="CHR A12" />
                    <pin number="27" function="CHR A15" />
                    <pin number="28" function="NC" />
                </chip>
            </board>
        </cartridge>
    </game>`

**Comment by carmiker** [comment]
The real fix is to expand the maximum PRG size for VRC2-based games.
Here is the fix in the upstream repo: https://gitlab.com/jgemu/nestopia/-/commit/c12231720f40f132712c59bb183baa4a9a872b81
