### ISSUE TITLE
Garbage pail kids and full quiet issues

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#414]
Both garbage pail kids and full quiet exhibit issues on nestopia.  They both run on the same board/mapper. 

Garbage pail kids crashes after selecting a difficulty and full quiet results in insta-death and scrambled graphics upon starting the first level. 

Not sure if it's a database fix or something rooted deeper in the core code. 

Tested on the latest version released just a few hours ago. 

BTW rdanbrook, glad to see you still plugging away and keeping nestopia "undead". 😁

**Comment by rdanbrook** [comment]
This will be merged in the next release, it is already fixed in the upstream branch, so I'll consider this problem solved.
