### ISSUE TITLE
Recent builds no longer allow configuring hotkeys

### ISSUE THREAD

**Issue by endlisnis** [0ldsk00l/nestopia#415]
Years ago, I used Nestopia and the input configuration dialog has a long list of hotkeys that could be configured.

When I ran it recently, I was surprised to find a very basic input configuration GUI: 
![image](https://github.com/0ldsk00l/nestopia/assets/3651887/077b9e05-6d9a-4f06-807c-8e8a4974978e)

No way to configure hotkeys for quick loading or saving, or anything else.  Just basic controller functionality.

I see a file called ~/.config/nestopia/nestopia.conf, which seems to have configuration for lots of hotkeys, but I don't know how to map some of those long numbers to keys.  For example:

`qsave1=65474`

I'm running v1.52.1 on Fedora Linux (Cinnamon desktop).

**Comment by rdanbrook** [comment]
The values are FLTK enum values:
https://www.fltk.org/doc-1.3/Enumerations_8H.html
Those are in hex notation, so they'll have to be converted to decimal. Yeah, I know it sucks. That's why I'm rewriting the entire UI in modern C++ as we speak... :).

**Comment by endlisnis** [comment]
OK.  "qsave1=65474" in hex is 0xffc2, but `ffc2` does not appear in that linked file.

**Comment by rdanbrook** [comment]
The F keys are weird, they use FL_F + the number of the key:
F0: 65469 == ffbd
F1: 65470 == ffbe
F2: 65471 == ffbf
F3: 65472 == ffc0
F4: 65473 == ffc1
F5: 65474 == ffc2
F6: 65475 == ffc3
F7: 65476 == ffc4
F8: 65477 == ffc5
F9: 65478 == ffc6
F10: 65479 == ffc7
F11: 65480 == ffc8
F12: 65481 == ffc9
