### ISSUE TITLE
All text is tiny on 4k screen

### ISSUE THREAD

**Issue by endlisnis** [0ldsk00l/nestopia#416]
I'm running v1.52.1 in Fedora Linux (Cinnamon Spin).

I have a 4k screen, with 200% display scaling enabled.

Nestopia seems to ignore my display scaling setting and appears the same regardless of display scaling.

The menu items for Nestopia are tiny (they are the size I would expect with no display scaling).

This is not limited to menu items, all text seems to be very small (the about dialog, status updates during saves, ...)

**Comment by rdanbrook** [comment]
Support for text scaling is coming in FLTK 1.4. I'll leave this open just to make sure I don't forget to address it when I port to FLTK 1.4.

**Comment by endlisnis** [comment]
Thanks.  Any idea when you expect to port it to FLTK 1.4?

**Comment by rdanbrook** [comment]
It depends on when FLTK 1.4 is released. It's really hard to tell where they are with that. I may also use Qt6... the important part of the ongoing rewrite is that the code is finally in a clean enough state to be reusable, so it shouldn't be hard to switch toolkits in the future if need be. That said, FTLK 1.4 is being worked on regularly, so it could happen any time for all I know.
