### ISSUE TITLE
Keyboard shortcuts don't activate menu items

### ISSUE THREAD

**Issue by endlisnis** [0ldsk00l/nestopia#417]
When running in Fedora 40 (or 39), Pressing "Alt+F" does not activate the "File" menu.  

The menu has 3 items 

<ins>F</ins>ile   <ins>E</ins>mulator   <ins>H</ins>elp

Pressing Alt+F, Alt+E and Alt+H do nothing.  I would expect them to activate the respective menus.

**Comment by rdanbrook** [comment]
Fixed in latest revision
