### ISSUE TITLE
rom dependant keyboard mapping issue

### ISSUE THREAD

**Issue by atalkingegg** [0ldsk00l/nestopia#418]
For external arcade joystick hardware keyboard reasons, I've mapped the following keys...
W, A, S, D => up, left, down, right
H, J, K, L => B, A, select, start

All keys map and work perfectly well for "Metroid (U).nes"
The (L) button does not map to start for  "Super Mario Bros (E).nes" (it's ignored), but the return key can be mapped and works fine as the start button.

Tested on 1.52.0 and 1.52.1, on MacOS and Raspberry Pi. 
Thanks!

**Comment by dragon2snow** [comment]
the L key also maps the functionality of 2P？

**Comment by atalkingegg** [comment]
Dragon2Snow is right, the work around is to map the 2nd player keys out of the way first, then 1st player buttons can be mapped to whatever's left. It's odd that it works on some games (single player only?) but hits this issue on others (multi-player). It would be a nice feature to show all the mapped keys with conflicts highlighted.
This issue can be closed.

**Comment by dragon2snow** [comment]
The SMB game may have issues processing input.

**Comment by rdanbrook** [comment]
I'll leave this open until the rewrite is done. The input configuration will be entirely redone, and include support for far more devices. I will consider a way to warn if a key is already defined, but it may be difficult considering the number of input devices that can be configured. For instance, maybe you want to play Pokkun Moguraa using the same keys as the Power Pad, but those will never be plugged in at the same time.

**Comment by dragon2snow** [comment]
> Dragon2Snow is right, the work around is to map the 2nd player keys out of the way first, then 1st player buttons can be mapped to whatever's left. It's odd that it works on some games (single player only?) but hits this issue on others (multi-player). It would be a nice feature to show all the mapped keys with conflicts highlighted. This issue can be closed.

On real consoles or other emulators, SMB is the game

When P2 holds down the directional key "down", P1's "START" is invalid
