### ISSUE TITLE
Add support for mapper 555

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#420]
Is it possible to add support for mapper 555? The Nintendo campus challenge mapper?

I believe support was added recently in fceultra retroarch.

Thanks for considering! It would be great to have this up and running in Nestopia undead and Nestopia retroarch!

**Comment by carmiker** [comment]
Hey @joepogo, I will try to get this in for the next upstream release.

**Comment by joepogo** [comment]
Thank you as always for your astounding work @carmiker! It'll be a nice little piece of history to add y to Nestopia undead and jge! 👊

**Comment by joepogo** [comment]
Hey @carmiker , just checking in. 

Any luck with this one so far? Just wondering if it's possible to get this implemented here and into retroarch as well. 

Anyways hope you're doing well buddy! 👊😁

**Comment by carmiker** [comment]
@joepogo I started working on it a few weeks ago but didn't finish it. The available documentation is not the clearest. I would like to get it done before I tag a new release, but if it seems insurmountable it will be coming in the release after that.

**Comment by joepogo** [comment]
No worries buddy! It'll be pretty neat to have this little piece of history working on Nestopia! 👍

**Comment by carmiker** [comment]
It's done.
