### ISSUE TITLE
i keep accidentally hitting the rewind button

### ISSUE THREAD

**Issue by squidman-cyber** [0ldsk00l/nestopia#422]
I would like to know how to disable it from my joystick left trigger button, i am using the flatpak version 1.51.1..is there a .conf file i can edit for this?

**Comment by rdanbrook** [comment]
I believe it should be at ~/.config/nestopia/input.conf in that version, and you can just blank it out.

I also highly recommend building the latest revision from source. It's really a lot better in every possible way.
