### ISSUE TITLE
I want to change the renderer

### ISSUE THREAD

**Issue by squidman-cyber** [0ldsk00l/nestopia#423]
I don't have that option in configuration>video but i noticed there is an option in software manager under linux mint to change it(in the screenshot) i have compiled and i have tried the flathub version I'm getting a weird flickering issue and I just want to change it to to see if that resolves the issue...

**Comment by rdanbrook** [comment]
When you say you compiled it, do you mean the latest revision from the master branch?

The flatpak is seriously out of date, a lot of fixes have been done since then. It's years old. I recommend not using that version.

The most recent revision on the master branch supports OpenGL 2.1, 3.1, and GLES 3.0. One of those should work for you.

**Comment by squidman-cyber** [comment]
I tried to compile it from the master branch but I did not see the executable in the directory after i ran make install....unlike the 1.52.1.tar.gz I could just run it with ./nestopia ..could you please tell me what i am doing wrong?

**Comment by rdanbrook** [comment]
From a freshly cloned repo, do the following:
`autoreconf -vif`
`./configure`
`make`

This should build everything. You can run the binary from that directory, or you can do `make install` to make it available globally.

**Comment by squidman-cyber** [comment]
It compiles fine but I can't seem to find the binary file ..how do I run it once it is built? btw the scanline thing with the standard filter looks great in windows 10..I want to get it working in linux because I have a screen tearing issue in full screen with it in windows 10

**Comment by rdanbrook** [comment]
The binary should be `nestopia` in the root of the repo. So after building, you should just be able to execute `./nestopia` to start it up. You can also use the path to the ROM as an argument if you don't want to browse for it using the GUI.

**Comment by squidman-cyber** [comment]
I got it compile properly with sudo make install...
