### ISSUE TITLE
Joystick "up" input incorrectly mapped in settings dialog

### ISSUE THREAD

**Issue by sylvainhalle** [0ldsk00l/nestopia#424]
If mapping inputs from the Configuration/Input dialog, the input for "up" is overwritten with the input for "right". Opening inputs.conf confirms that these two inputs are configured identically. Modifying that configuration file manually to the correct setting solves the problem.

**Comment by rdanbrook** [comment]
Are you using the master branch or a tagged release? I can't reproduce this on the master branch.

I think I need to tag a new release soon.

**Comment by sylvainhalle** [comment]
I am using release 1.52 installed from the Ubuntu repository.

**Comment by rdanbrook** [comment]
I recommend building the master branch, it is better in every possible way. I will start gearing up for a new release too, I can't be having such nasty bugs out in the wild.

**Comment by sylvainhalle** [comment]
I commented out the line using that function and could compile. I confirm that the joystick settings work correctly in the new version of the dialog.
