### ISSUE TITLE
Mapper 30 issues with Adventure of panzer 3

### ISSUE THREAD

**Issue by joepogo** [0ldsk00l/nestopia#429]
The support for mapper 30 appears to be slightly broken in the most recent and older builds that I've tested. 

Adventure of panzer 3 will only boot to a green screen. 

I haven't tested every mapper 30 game but Adventure of panzer 3 is definitely not working. It's probably safe to assume there are others that do not.

**Comment by joepogo** [comment]
Hey @dragon2snow I'm not 100 percent sure if the rom is publicly available yet but it is dumped and out there floating around.

I have a copy of the rom if it helps someone get it working correctly. Just let me know if you need it.

**Comment by carmiker** [comment]
A friend who has obtained a copy by what I will assume are legal means has confirmed with me that it works. He tested version 1.1 only. I tested the demo, and it works for me. @joepogo are you using version 1.0?

**Comment by dragon2snow** [comment]
> Hey @dragon2snow I'm not 100 percent sure if the rom is publicly available yet but it is dumped and out there floating around.
> 
> I have a copy of the rom if it helps someone get it working correctly. Just let me know if you need it.
It shouldn't be possible, as there's no ROM, and I can't confirm where the problem lies. I see that Carmiker has tested it and found no issues, since most of the 30 are UxROM.

**Comment by joepogo** [comment]
Most likely you're playing the demo version. 

The rom I have is dumped from the official release. (The paid version)

It works on mesen but none of the nestopia's. Let me know and I can send it your way.

**Comment by dragon2snow** [comment]
4325692@qq.com
If you want us to test it and trust us, you can send a copy (1.0, 1.1) to us. At the very least, I won't make it public.

**Comment by joepogo** [comment]
Ok, I sent it you @dragon2snow . Let me know if you want it too @carmiker . 👍👊

**Comment by joepogo** [comment]
Thanks for cleaning up the posts @rdanbrook . 

I wasn't too comfortable posting about the rom image for this game. Just wanted to get it out there that it isn't working correctly. 😁

**Comment by dragon2snow** [comment]
`NES_POKE_AD(UxRom,8000_0)
			{
				if (!hasbattery)
					data = GetBusData(address,data);
				chr.SwapBank<SIZE_8K, 0x0000>( ( data >> 5) & 0x3 );
				prg.SwapBank<SIZE_16K, 0x0000>( ( data ) & 0x1f );
				if ( mirr == Type::NMT_FOURSCREEN )
					ppu.SetMirroring( ( data & 0x80 ) ? Ppu::NMT_1 : Ppu::NMT_0 );
			}`


Let me briefly explain the reason:

According to the UNROM512 WIKI definition, when not using battery save memory but instead using flash save or no save, you need to use GetBusData. However, it has been found that several mapper 30 games currently don't implement GetBusData.

To execute without modifying the code, please add the battery flag to the NES header of the 1.1 ROM. That should work.

**Comment by carmiker** [comment]
@dragon2snow it seems the battery flag is already there. Does this game even have saves? I think the answer is no. It seems like setting the "battery" flag in the header is a hack to get emulators to not emulate bus conflicts. It isn't actually writing to flash ROM. Dodgy.

If the header is NES 2.0, Nestopia doesn't currently do anything special if the battery flag on and there is no PRG NVRAM or CHR NVRAM size also defined.

I've been able to confirm that the difference between the working version and the one @joepogo has is that one uses the iNES header format and the other uses NES 2.0. One version might have been dumped from a cart while the other was downloaded after paying the fee for the .nes file. I won't speculate as to which is which.

I believe the fix will be to allow NES 2.0 headered ROMs with the battery flag set, but without specifying PRG NVRAM or CHR NVRAM sizes, perhaps only for the special case of mapper 30. It appears this is actually how the mapper was designed to work.

References:
https://www.nesdev.org/wiki/UNROM_512#Mapper

**Comment by carmiker** [comment]
I've pushed the solution, please let me know if it works for you @joepogo and @dragon2snow .

**Comment by carmiker** [comment]
I've received confirmation that it works.
