### ISSUE TITLE
Implement proper RAMBO-1 (mapper 64) IRQ counter behaviour 

### ISSUE THREAD

**Issue by koitsu** [0ldsk00l/nestopia#89]
It seems games using the RAMBO-1 (mapper 64) IRQ counter do not behave properly in Nestopia.  This is understandable given that the difference between it and MMC3 has only recently (~past year) come to light and this information has not been commonly disseminated.

Full details: http://forums.nesdev.com/viewtopic.php?f=3&t=11525

Be sure to read the referenced link in that thread.

And some logic documentation, as well as a recommended alternate approach that might fix Hard Drivin':

http://wiki.nesdev.com/w/index.php/RAMBO-1
http://wiki.nesdev.com/w/index.php/Talk:RAMBO-1

**Comment by joepogo** [comment]
Hey Koitsu, is this mapper related to tengen by chance?

**Comment by koitsu** [comment]
Did you look at the nesdev wiki links provided in the original post?  Please do.

**Comment by joepogo** [comment]
Yea, shortly after I posted this, I did look it up. I see my shinobi ticket and the skull and crossbones are on the same mapper, so yesit is Def tengen related. :)

**Comment by joepogo** [comment]
hey rdanbrook, any luck with this one? Ive been going back ad forth with dragon about it, but you know how that goes.

**Comment by rdanbrook** [comment]
This is being handled in the jgemu repo.
